package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Maps the `admin_ssl_configuration` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "admin_ssl_configuration")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class AdminSslConfigurationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "certificate_file_reference", length = 1024)
  private String certificateFileReference;

  @Column(name = "private_key_file_reference", length = 1024)
  private String privateKeyFileReference;

  @Column(name = "certificate_status", length = 64)
  private String certificateStatus;

  @Column(name = "expires_at")
  private LocalDate expiresAt;

  @Column(name = "is_active")
  private Boolean isActive;

  @Column(name = "updated_by", length = 255)
  private String updatedBy;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getCertificateFileReference() { return certificateFileReference; }
  public void setCertificateFileReference(String certificateFileReference) { this.certificateFileReference = certificateFileReference; }

  public String getPrivateKeyFileReference() { return privateKeyFileReference; }
  public void setPrivateKeyFileReference(String privateKeyFileReference) { this.privateKeyFileReference = privateKeyFileReference; }

  public String getCertificateStatus() { return certificateStatus; }
  public void setCertificateStatus(String certificateStatus) { this.certificateStatus = certificateStatus; }

  public LocalDate getExpiresAt() { return expiresAt; }
  public void setExpiresAt(LocalDate expiresAt) { this.expiresAt = expiresAt; }

  public Boolean getIsActive() { return isActive; }
  public void setIsActive(Boolean isActive) { this.isActive = isActive; }

  public String getUpdatedBy() { return updatedBy; }
  public void setUpdatedBy(String updatedBy) { this.updatedBy = updatedBy; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
