package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `approved_clause` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "approved_clause")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ApprovedClauseEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "identifier", length = 255)
  private String identifier;

  @Column(name = "title", length = 255)
  private String title;

  @Column(name = "body", columnDefinition = "LONGTEXT")
  private String body;

  @Column(name = "category", length = 64)
  private String category;

  @Column(name = "applicable_jurisdictions", columnDefinition = "LONGTEXT")
  private String applicableJurisdictions;

  @Column(name = "inclusion_rule", columnDefinition = "LONGTEXT")
  private String inclusionRule;

  @Column(name = "required_combinations", columnDefinition = "LONGTEXT")
  private String requiredCombinations;

  @Column(name = "prohibited_combinations", columnDefinition = "LONGTEXT")
  private String prohibitedCombinations;

  @Column(name = "mandatory")
  private Boolean mandatory;

  @Column(name = "effective_from")
  private Instant effectiveFrom;

  @Column(name = "retirement_date")
  private Instant retirementDate;

  @Column(name = "version")
  private Double version;

  @Column(name = "required_variables", columnDefinition = "LONGTEXT")
  private String requiredVariables;

  @Column(name = "modification_requires_reapproval")
  private Boolean modificationRequiresReapproval;

  @Column(name = "legal_signoff", columnDefinition = "LONGTEXT")
  private String legalSignoff;

  @Column(name = "is_current")
  private Boolean isCurrent;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getIdentifier() { return identifier; }
  public void setIdentifier(String identifier) { this.identifier = identifier; }

  public String getTitle() { return title; }
  public void setTitle(String title) { this.title = title; }

  public String getBody() { return body; }
  public void setBody(String body) { this.body = body; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getApplicableJurisdictions() { return applicableJurisdictions; }
  public void setApplicableJurisdictions(String applicableJurisdictions) { this.applicableJurisdictions = applicableJurisdictions; }

  public String getInclusionRule() { return inclusionRule; }
  public void setInclusionRule(String inclusionRule) { this.inclusionRule = inclusionRule; }

  public String getRequiredCombinations() { return requiredCombinations; }
  public void setRequiredCombinations(String requiredCombinations) { this.requiredCombinations = requiredCombinations; }

  public String getProhibitedCombinations() { return prohibitedCombinations; }
  public void setProhibitedCombinations(String prohibitedCombinations) { this.prohibitedCombinations = prohibitedCombinations; }

  public Boolean getMandatory() { return mandatory; }
  public void setMandatory(Boolean mandatory) { this.mandatory = mandatory; }

  public Instant getEffectiveFrom() { return effectiveFrom; }
  public void setEffectiveFrom(Instant effectiveFrom) { this.effectiveFrom = effectiveFrom; }

  public Instant getRetirementDate() { return retirementDate; }
  public void setRetirementDate(Instant retirementDate) { this.retirementDate = retirementDate; }

  public Double getVersion() { return version; }
  public void setVersion(Double version) { this.version = version; }

  public String getRequiredVariables() { return requiredVariables; }
  public void setRequiredVariables(String requiredVariables) { this.requiredVariables = requiredVariables; }

  public Boolean getModificationRequiresReapproval() { return modificationRequiresReapproval; }
  public void setModificationRequiresReapproval(Boolean modificationRequiresReapproval) { this.modificationRequiresReapproval = modificationRequiresReapproval; }

  public String getLegalSignoff() { return legalSignoff; }
  public void setLegalSignoff(String legalSignoff) { this.legalSignoff = legalSignoff; }

  public Boolean getIsCurrent() { return isCurrent; }
  public void setIsCurrent(Boolean isCurrent) { this.isCurrent = isCurrent; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
