package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `audience_member` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "audience_member")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class AudienceMemberEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "email", length = 255)
  private String email;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "audience_type", length = 64)
  private String audienceType;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "category_interests", columnDefinition = "LONGTEXT")
  private String categoryInterests;

  @Column(name = "participated_before")
  private Boolean participatedBefore;

  @Column(name = "entry_count")
  private Double entryCount;

  @Column(name = "vote_count")
  private Double voteCount;

  @Column(name = "source", length = 64)
  private String source;

  @Column(name = "organisation_id", length = 255)
  private String organisationId;

  @Column(name = "organisation_name", length = 255)
  private String organisationName;

  @Column(name = "is_registered_user")
  private Boolean isRegisteredUser;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "unsubscribed_at")
  private Instant unsubscribedAt;

  @Column(name = "welcomed_at")
  private Instant welcomedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getEmail() { return email; }
  public void setEmail(String email) { this.email = email; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getAudienceType() { return audienceType; }
  public void setAudienceType(String audienceType) { this.audienceType = audienceType; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getCategoryInterests() { return categoryInterests; }
  public void setCategoryInterests(String categoryInterests) { this.categoryInterests = categoryInterests; }

  public Boolean getParticipatedBefore() { return participatedBefore; }
  public void setParticipatedBefore(Boolean participatedBefore) { this.participatedBefore = participatedBefore; }

  public Double getEntryCount() { return entryCount; }
  public void setEntryCount(Double entryCount) { this.entryCount = entryCount; }

  public Double getVoteCount() { return voteCount; }
  public void setVoteCount(Double voteCount) { this.voteCount = voteCount; }

  public String getSource() { return source; }
  public void setSource(String source) { this.source = source; }

  public String getOrganisationId() { return organisationId; }
  public void setOrganisationId(String organisationId) { this.organisationId = organisationId; }

  public String getOrganisationName() { return organisationName; }
  public void setOrganisationName(String organisationName) { this.organisationName = organisationName; }

  public Boolean getIsRegisteredUser() { return isRegisteredUser; }
  public void setIsRegisteredUser(Boolean isRegisteredUser) { this.isRegisteredUser = isRegisteredUser; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getUnsubscribedAt() { return unsubscribedAt; }
  public void setUnsubscribedAt(Instant unsubscribedAt) { this.unsubscribedAt = unsubscribedAt; }

  public Instant getWelcomedAt() { return welcomedAt; }
  public void setWelcomedAt(Instant welcomedAt) { this.welcomedAt = welcomedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
