package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `audit_review` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "audit_review")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class AuditReviewEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "competition_title", length = 255)
  private String competitionTitle;

  @Column(name = "panel_id", length = 255)
  private String panelId;

  @Column(name = "auditor_user_id", length = 255)
  private String auditorUserId;

  @Column(name = "auditor_name", length = 255)
  private String auditorName;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "pre_launch", columnDefinition = "LONGTEXT")
  private String preLaunch;

  @Column(name = "checklist", columnDefinition = "LONGTEXT")
  private String checklist;

  @Column(name = "recomputed", columnDefinition = "LONGTEXT")
  private String recomputed;

  @Column(name = "vote_integrity", columnDefinition = "LONGTEXT")
  private String voteIntegrity;

  @Column(name = "random_sample_entry_ids", columnDefinition = "LONGTEXT")
  private String randomSampleEntryIds;

  @Column(name = "random_sample_judge_ids", columnDefinition = "LONGTEXT")
  private String randomSampleJudgeIds;

  @Column(name = "sign_off_by", length = 255)
  private String signOffBy;

  @Column(name = "sign_off_name", length = 255)
  private String signOffName;

  @Column(name = "sign_off_at")
  private Instant signOffAt;

  @Column(name = "sign_off_notes", columnDefinition = "LONGTEXT")
  private String signOffNotes;

  @Column(name = "routed_to", length = 64)
  private String routedTo;

  @Column(name = "routing_reason", columnDefinition = "LONGTEXT")
  private String routingReason;

  @Column(name = "re_audit_count")
  private Double reAuditCount;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getCompetitionTitle() { return competitionTitle; }
  public void setCompetitionTitle(String competitionTitle) { this.competitionTitle = competitionTitle; }

  public String getPanelId() { return panelId; }
  public void setPanelId(String panelId) { this.panelId = panelId; }

  public String getAuditorUserId() { return auditorUserId; }
  public void setAuditorUserId(String auditorUserId) { this.auditorUserId = auditorUserId; }

  public String getAuditorName() { return auditorName; }
  public void setAuditorName(String auditorName) { this.auditorName = auditorName; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getPreLaunch() { return preLaunch; }
  public void setPreLaunch(String preLaunch) { this.preLaunch = preLaunch; }

  public String getChecklist() { return checklist; }
  public void setChecklist(String checklist) { this.checklist = checklist; }

  public String getRecomputed() { return recomputed; }
  public void setRecomputed(String recomputed) { this.recomputed = recomputed; }

  public String getVoteIntegrity() { return voteIntegrity; }
  public void setVoteIntegrity(String voteIntegrity) { this.voteIntegrity = voteIntegrity; }

  public String getRandomSampleEntryIds() { return randomSampleEntryIds; }
  public void setRandomSampleEntryIds(String randomSampleEntryIds) { this.randomSampleEntryIds = randomSampleEntryIds; }

  public String getRandomSampleJudgeIds() { return randomSampleJudgeIds; }
  public void setRandomSampleJudgeIds(String randomSampleJudgeIds) { this.randomSampleJudgeIds = randomSampleJudgeIds; }

  public String getSignOffBy() { return signOffBy; }
  public void setSignOffBy(String signOffBy) { this.signOffBy = signOffBy; }

  public String getSignOffName() { return signOffName; }
  public void setSignOffName(String signOffName) { this.signOffName = signOffName; }

  public Instant getSignOffAt() { return signOffAt; }
  public void setSignOffAt(Instant signOffAt) { this.signOffAt = signOffAt; }

  public String getSignOffNotes() { return signOffNotes; }
  public void setSignOffNotes(String signOffNotes) { this.signOffNotes = signOffNotes; }

  public String getRoutedTo() { return routedTo; }
  public void setRoutedTo(String routedTo) { this.routedTo = routedTo; }

  public String getRoutingReason() { return routingReason; }
  public void setRoutingReason(String routingReason) { this.routingReason = routingReason; }

  public Double getReAuditCount() { return reAuditCount; }
  public void setReAuditCount(Double reAuditCount) { this.reAuditCount = reAuditCount; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
