package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `audit_finding` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "audit_finding")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class AuditFindingEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "review_id", length = 255)
  private String reviewId;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "severity", length = 64)
  private String severity;

  @Column(name = "category", length = 64)
  private String category;

  @Column(name = "detail", columnDefinition = "LONGTEXT")
  private String detail;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "resolution", length = 255)
  private String resolution;

  @Column(name = "created_by", length = 255)
  private String createdBy;

  @Column(name = "created_by_name", length = 255)
  private String createdByName;

  @Column(name = "created_at")
  private Instant createdAt;

  @Column(name = "resolved_by", length = 255)
  private String resolvedBy;

  @Column(name = "resolved_at")
  private Instant resolvedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getReviewId() { return reviewId; }
  public void setReviewId(String reviewId) { this.reviewId = reviewId; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getSeverity() { return severity; }
  public void setSeverity(String severity) { this.severity = severity; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getDetail() { return detail; }
  public void setDetail(String detail) { this.detail = detail; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getResolution() { return resolution; }
  public void setResolution(String resolution) { this.resolution = resolution; }

  public String getCreatedBy() { return createdBy; }
  public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }

  public String getCreatedByName() { return createdByName; }
  public void setCreatedByName(String createdByName) { this.createdByName = createdByName; }

  public Instant getCreatedAt() { return createdAt; }
  public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

  public String getResolvedBy() { return resolvedBy; }
  public void setResolvedBy(String resolvedBy) { this.resolvedBy = resolvedBy; }

  public Instant getResolvedAt() { return resolvedAt; }
  public void setResolvedAt(Instant resolvedAt) { this.resolvedAt = resolvedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
