package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `calibration_score` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "calibration_score")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CalibrationScoreEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "panel_id", length = 255)
  private String panelId;

  @Column(name = "judge_profile_id", length = 1024)
  private String judgeProfileId;

  @Column(name = "judge_name", length = 255)
  private String judgeName;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "scores", columnDefinition = "LONGTEXT")
  private String scores;

  @Column(name = "comments", columnDefinition = "LONGTEXT")
  private String comments;

  @Column(name = "at")
  private Instant at;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPanelId() { return panelId; }
  public void setPanelId(String panelId) { this.panelId = panelId; }

  public String getJudgeProfileId() { return judgeProfileId; }
  public void setJudgeProfileId(String judgeProfileId) { this.judgeProfileId = judgeProfileId; }

  public String getJudgeName() { return judgeName; }
  public void setJudgeName(String judgeName) { this.judgeName = judgeName; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getScores() { return scores; }
  public void setScores(String scores) { this.scores = scores; }

  public String getComments() { return comments; }
  public void setComments(String comments) { this.comments = comments; }

  public Instant getAt() { return at; }
  public void setAt(Instant at) { this.at = at; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
