package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge_compliance_assessment` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge_compliance_assessment")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeComplianceAssessmentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "fired_triggers", columnDefinition = "LONGTEXT")
  private String firedTriggers;

  @Column(name = "classification", length = 64)
  private String classification;

  @Column(name = "assessed_at")
  private Instant assessedAt;

  @Column(name = "rule_versions_used", columnDefinition = "LONGTEXT")
  private String ruleVersionsUsed;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getFiredTriggers() { return firedTriggers; }
  public void setFiredTriggers(String firedTriggers) { this.firedTriggers = firedTriggers; }

  public String getClassification() { return classification; }
  public void setClassification(String classification) { this.classification = classification; }

  public Instant getAssessedAt() { return assessedAt; }
  public void setAssessedAt(Instant assessedAt) { this.assessedAt = assessedAt; }

  public String getRuleVersionsUsed() { return ruleVersionsUsed; }
  public void setRuleVersionsUsed(String ruleVersionsUsed) { this.ruleVersionsUsed = ruleVersionsUsed; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
