package com.fiftythree.challenges.entity;

import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Generated by migration/generate-entities.cjs. Add query methods in a separate
 * interface rather than here — this file is overwritten on regeneration.
 */
public interface ChallengeRecommendationRepository extends JpaRepository<ChallengeRecommendationEntity, String> {
}
