package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "title", length = 255)
  private String title;

  @Column(name = "theme", length = 255)
  private String theme;

  @Column(name = "category", length = 64)
  private String category;

  @Column(name = "category_id", length = 255)
  private String categoryId;

  @Column(name = "content_type", length = 64)
  private String contentType;

  @Column(name = "divisions", columnDefinition = "LONGTEXT")
  private String divisions;

  @Column(name = "niche_tags", columnDefinition = "LONGTEXT")
  private String nicheTags;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "stage", length = 64)
  private String stage;

  @Column(name = "season", length = 255)
  private String season;

  @Column(name = "parent_challenge_id", length = 255)
  private String parentChallengeId;

  @Column(name = "host_organisation_id", length = 255)
  private String hostOrganisationId;

  @Column(name = "brief", columnDefinition = "LONGTEXT")
  private String brief;

  @Column(name = "cover_image", length = 1024)
  private String coverImage;

  @Column(name = "starts_at")
  private Instant startsAt;

  @Column(name = "submission_ends_at")
  private Instant submissionEndsAt;

  @Column(name = "voting_ends_at")
  private Instant votingEndsAt;

  @Column(name = "lifecycle_status", length = 64)
  private String lifecycleStatus;

  @Column(name = "source", length = 64)
  private String source;

  @Column(name = "upstream_id", length = 255)
  private String upstreamId;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getTitle() { return title; }
  public void setTitle(String title) { this.title = title; }

  public String getTheme() { return theme; }
  public void setTheme(String theme) { this.theme = theme; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getCategoryId() { return categoryId; }
  public void setCategoryId(String categoryId) { this.categoryId = categoryId; }

  public String getContentType() { return contentType; }
  public void setContentType(String contentType) { this.contentType = contentType; }

  public String getDivisions() { return divisions; }
  public void setDivisions(String divisions) { this.divisions = divisions; }

  public String getNicheTags() { return nicheTags; }
  public void setNicheTags(String nicheTags) { this.nicheTags = nicheTags; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getStage() { return stage; }
  public void setStage(String stage) { this.stage = stage; }

  public String getSeason() { return season; }
  public void setSeason(String season) { this.season = season; }

  public String getParentChallengeId() { return parentChallengeId; }
  public void setParentChallengeId(String parentChallengeId) { this.parentChallengeId = parentChallengeId; }

  public String getHostOrganisationId() { return hostOrganisationId; }
  public void setHostOrganisationId(String hostOrganisationId) { this.hostOrganisationId = hostOrganisationId; }

  public String getBrief() { return brief; }
  public void setBrief(String brief) { this.brief = brief; }

  public String getCoverImage() { return coverImage; }
  public void setCoverImage(String coverImage) { this.coverImage = coverImage; }

  public Instant getStartsAt() { return startsAt; }
  public void setStartsAt(Instant startsAt) { this.startsAt = startsAt; }

  public Instant getSubmissionEndsAt() { return submissionEndsAt; }
  public void setSubmissionEndsAt(Instant submissionEndsAt) { this.submissionEndsAt = submissionEndsAt; }

  public Instant getVotingEndsAt() { return votingEndsAt; }
  public void setVotingEndsAt(Instant votingEndsAt) { this.votingEndsAt = votingEndsAt; }

  public String getLifecycleStatus() { return lifecycleStatus; }
  public void setLifecycleStatus(String lifecycleStatus) { this.lifecycleStatus = lifecycleStatus; }

  public String getSource() { return source; }
  public void setSource(String source) { this.source = source; }

  public String getUpstreamId() { return upstreamId; }
  public void setUpstreamId(String upstreamId) { this.upstreamId = upstreamId; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
