package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge_recommendation` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge_recommendation")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeRecommendationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "response_id", length = 255)
  private String responseId;

  @Column(name = "host_organisation_id", length = 255)
  private String hostOrganisationId;

  @Column(name = "top_mechanics", columnDefinition = "LONGTEXT")
  private String topMechanics;

  @Column(name = "top_categories", columnDefinition = "LONGTEXT")
  private String topCategories;

  @Column(name = "top_modes", columnDefinition = "LONGTEXT")
  private String topModes;

  @Column(name = "top_audiences", columnDefinition = "LONGTEXT")
  private String topAudiences;

  @Column(name = "top_scoring", columnDefinition = "LONGTEXT")
  private String topScoring;

  @Column(name = "top_evidence", columnDefinition = "LONGTEXT")
  private String topEvidence;

  @Column(name = "top_pathways", columnDefinition = "LONGTEXT")
  private String topPathways;

  @Column(name = "compliance_flags", columnDefinition = "LONGTEXT")
  private String complianceFlags;

  @Column(name = "rationale_summary", columnDefinition = "LONGTEXT")
  private String rationaleSummary;

  @Column(name = "service_tier_id", length = 255)
  private String serviceTierId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getResponseId() { return responseId; }
  public void setResponseId(String responseId) { this.responseId = responseId; }

  public String getHostOrganisationId() { return hostOrganisationId; }
  public void setHostOrganisationId(String hostOrganisationId) { this.hostOrganisationId = hostOrganisationId; }

  public String getTopMechanics() { return topMechanics; }
  public void setTopMechanics(String topMechanics) { this.topMechanics = topMechanics; }

  public String getTopCategories() { return topCategories; }
  public void setTopCategories(String topCategories) { this.topCategories = topCategories; }

  public String getTopModes() { return topModes; }
  public void setTopModes(String topModes) { this.topModes = topModes; }

  public String getTopAudiences() { return topAudiences; }
  public void setTopAudiences(String topAudiences) { this.topAudiences = topAudiences; }

  public String getTopScoring() { return topScoring; }
  public void setTopScoring(String topScoring) { this.topScoring = topScoring; }

  public String getTopEvidence() { return topEvidence; }
  public void setTopEvidence(String topEvidence) { this.topEvidence = topEvidence; }

  public String getTopPathways() { return topPathways; }
  public void setTopPathways(String topPathways) { this.topPathways = topPathways; }

  public String getComplianceFlags() { return complianceFlags; }
  public void setComplianceFlags(String complianceFlags) { this.complianceFlags = complianceFlags; }

  public String getRationaleSummary() { return rationaleSummary; }
  public void setRationaleSummary(String rationaleSummary) { this.rationaleSummary = rationaleSummary; }

  public String getServiceTierId() { return serviceTierId; }
  public void setServiceTierId(String serviceTierId) { this.serviceTierId = serviceTierId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
