package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge_draft` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge_draft")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeDraftEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "origin", length = 64)
  private String origin;

  @Column(name = "content_type", length = 64)
  private String contentType;

  @Column(name = "host_organisation_id", length = 255)
  private String hostOrganisationId;

  @Column(name = "recommendation_id", length = 255)
  private String recommendationId;

  @Column(name = "service_tier_id", length = 255)
  private String serviceTierId;

  @Column(name = "scale_band", length = 255)
  private String scaleBand;

  @Column(name = "program_scope", length = 64)
  private String programScope;

  @Column(name = "review_status", length = 64)
  private String reviewStatus;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "challenge_description", columnDefinition = "LONGTEXT")
  private String challengeDescription;

  @Column(name = "host_type", length = 255)
  private String hostType;

  @Column(name = "delivery_level", length = 255)
  private String deliveryLevel;

  @Column(name = "participant_range", length = 255)
  private String participantRange;

  @Column(name = "category", length = 255)
  private String category;

  @Column(name = "winner_method", length = 255)
  private String winnerMethod;

  @Column(name = "divisions", columnDefinition = "LONGTEXT")
  private String divisions;

  @Column(name = "addons", columnDefinition = "LONGTEXT")
  private String addons;

  @Column(name = "answers", columnDefinition = "LONGTEXT")
  private String answers;

  @Column(name = "admin_feedback", columnDefinition = "LONGTEXT")
  private String adminFeedback;

  @Column(name = "decline_reason", columnDefinition = "LONGTEXT")
  private String declineReason;

  @Column(name = "recommended_snapshot", columnDefinition = "LONGTEXT")
  private String recommendedSnapshot;

  @Column(name = "compliance_flags", columnDefinition = "LONGTEXT")
  private String complianceFlags;

  @Column(name = "deliverables", columnDefinition = "LONGTEXT")
  private String deliverables;

  @Column(name = "is_template")
  private Boolean isTemplate;

  @Column(name = "template_name", length = 255)
  private String templateName;

  @Column(name = "template_family_id", length = 255)
  private String templateFamilyId;

  @Column(name = "template_version")
  private Double templateVersion;

  @Column(name = "template_status", length = 64)
  private String templateStatus;

  @Column(name = "previous_version_id", length = 255)
  private String previousVersionId;

  @Column(name = "superseded_by_id", length = 255)
  private String supersededById;

  @Column(name = "superseded_at")
  private Instant supersededAt;

  @Column(name = "superseded_by_user", length = 255)
  private String supersededByUser;

  @Column(name = "published_at")
  private Instant publishedAt;

  @Column(name = "published_by", length = 255)
  private String publishedBy;

  @Column(name = "archived_at")
  private Instant archivedAt;

  @Column(name = "archived_by", length = 255)
  private String archivedBy;

  @Column(name = "archive_reason", columnDefinition = "LONGTEXT")
  private String archiveReason;

  @Column(name = "primary_category_id", length = 255)
  private String primaryCategoryId;

  @Column(name = "subcategory_id", length = 255)
  private String subcategoryId;

  @Column(name = "service_tier", length = 64)
  private String serviceTier;

  @Column(name = "template_tags", columnDefinition = "LONGTEXT")
  private String templateTags;

  @Column(name = "concept_pack", columnDefinition = "LONGTEXT")
  private String conceptPack;

  @Column(name = "rules_pack", columnDefinition = "LONGTEXT")
  private String rulesPack;

  @Column(name = "brand_pack", columnDefinition = "LONGTEXT")
  private String brandPack;

  @Column(name = "participation_pack", columnDefinition = "LONGTEXT")
  private String participationPack;

  @Column(name = "operations_pack", columnDefinition = "LONGTEXT")
  private String operationsPack;

  @Column(name = "legal_pack", columnDefinition = "LONGTEXT")
  private String legalPack;

  @Column(name = "lock_map", columnDefinition = "LONGTEXT")
  private String lockMap;

  @Column(name = "template_recommendation_config", columnDefinition = "LONGTEXT")
  private String templateRecommendationConfig;

  @Column(name = "template_audit_log", columnDefinition = "LONGTEXT")
  private String templateAuditLog;

  @Column(name = "template_id", length = 255)
  private String templateId;

  @Column(name = "template_family_id_snapshot", length = 255)
  private String templateFamilyIdSnapshot;

  @Column(name = "template_version_number_snapshot")
  private Double templateVersionNumberSnapshot;

  @Column(name = "template_version_snapshot", columnDefinition = "LONGTEXT")
  private String templateVersionSnapshot;

  @Column(name = "template_snapshot_created_at")
  private Instant templateSnapshotCreatedAt;

  @Column(name = "host_brand_overrides", columnDefinition = "LONGTEXT")
  private String hostBrandOverrides;

  @Column(name = "admin_brand_adjustments", columnDefinition = "LONGTEXT")
  private String adminBrandAdjustments;

  @Column(name = "approved_brand_pack", columnDefinition = "LONGTEXT")
  private String approvedBrandPack;

  @Column(name = "approved_by", length = 255)
  private String approvedBy;

  @Column(name = "approved_at")
  private Instant approvedAt;

  @Column(name = "approval_locked")
  private Boolean approvalLocked;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getOrigin() { return origin; }
  public void setOrigin(String origin) { this.origin = origin; }

  public String getContentType() { return contentType; }
  public void setContentType(String contentType) { this.contentType = contentType; }

  public String getHostOrganisationId() { return hostOrganisationId; }
  public void setHostOrganisationId(String hostOrganisationId) { this.hostOrganisationId = hostOrganisationId; }

  public String getRecommendationId() { return recommendationId; }
  public void setRecommendationId(String recommendationId) { this.recommendationId = recommendationId; }

  public String getServiceTierId() { return serviceTierId; }
  public void setServiceTierId(String serviceTierId) { this.serviceTierId = serviceTierId; }

  public String getScaleBand() { return scaleBand; }
  public void setScaleBand(String scaleBand) { this.scaleBand = scaleBand; }

  public String getProgramScope() { return programScope; }
  public void setProgramScope(String programScope) { this.programScope = programScope; }

  public String getReviewStatus() { return reviewStatus; }
  public void setReviewStatus(String reviewStatus) { this.reviewStatus = reviewStatus; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getChallengeDescription() { return challengeDescription; }
  public void setChallengeDescription(String challengeDescription) { this.challengeDescription = challengeDescription; }

  public String getHostType() { return hostType; }
  public void setHostType(String hostType) { this.hostType = hostType; }

  public String getDeliveryLevel() { return deliveryLevel; }
  public void setDeliveryLevel(String deliveryLevel) { this.deliveryLevel = deliveryLevel; }

  public String getParticipantRange() { return participantRange; }
  public void setParticipantRange(String participantRange) { this.participantRange = participantRange; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getWinnerMethod() { return winnerMethod; }
  public void setWinnerMethod(String winnerMethod) { this.winnerMethod = winnerMethod; }

  public String getDivisions() { return divisions; }
  public void setDivisions(String divisions) { this.divisions = divisions; }

  public String getAddons() { return addons; }
  public void setAddons(String addons) { this.addons = addons; }

  public String getAnswers() { return answers; }
  public void setAnswers(String answers) { this.answers = answers; }

  public String getAdminFeedback() { return adminFeedback; }
  public void setAdminFeedback(String adminFeedback) { this.adminFeedback = adminFeedback; }

  public String getDeclineReason() { return declineReason; }
  public void setDeclineReason(String declineReason) { this.declineReason = declineReason; }

  public String getRecommendedSnapshot() { return recommendedSnapshot; }
  public void setRecommendedSnapshot(String recommendedSnapshot) { this.recommendedSnapshot = recommendedSnapshot; }

  public String getComplianceFlags() { return complianceFlags; }
  public void setComplianceFlags(String complianceFlags) { this.complianceFlags = complianceFlags; }

  public String getDeliverables() { return deliverables; }
  public void setDeliverables(String deliverables) { this.deliverables = deliverables; }

  public Boolean getIsTemplate() { return isTemplate; }
  public void setIsTemplate(Boolean isTemplate) { this.isTemplate = isTemplate; }

  public String getTemplateName() { return templateName; }
  public void setTemplateName(String templateName) { this.templateName = templateName; }

  public String getTemplateFamilyId() { return templateFamilyId; }
  public void setTemplateFamilyId(String templateFamilyId) { this.templateFamilyId = templateFamilyId; }

  public Double getTemplateVersion() { return templateVersion; }
  public void setTemplateVersion(Double templateVersion) { this.templateVersion = templateVersion; }

  public String getTemplateStatus() { return templateStatus; }
  public void setTemplateStatus(String templateStatus) { this.templateStatus = templateStatus; }

  public String getPreviousVersionId() { return previousVersionId; }
  public void setPreviousVersionId(String previousVersionId) { this.previousVersionId = previousVersionId; }

  public String getSupersededById() { return supersededById; }
  public void setSupersededById(String supersededById) { this.supersededById = supersededById; }

  public Instant getSupersededAt() { return supersededAt; }
  public void setSupersededAt(Instant supersededAt) { this.supersededAt = supersededAt; }

  public String getSupersededByUser() { return supersededByUser; }
  public void setSupersededByUser(String supersededByUser) { this.supersededByUser = supersededByUser; }

  public Instant getPublishedAt() { return publishedAt; }
  public void setPublishedAt(Instant publishedAt) { this.publishedAt = publishedAt; }

  public String getPublishedBy() { return publishedBy; }
  public void setPublishedBy(String publishedBy) { this.publishedBy = publishedBy; }

  public Instant getArchivedAt() { return archivedAt; }
  public void setArchivedAt(Instant archivedAt) { this.archivedAt = archivedAt; }

  public String getArchivedBy() { return archivedBy; }
  public void setArchivedBy(String archivedBy) { this.archivedBy = archivedBy; }

  public String getArchiveReason() { return archiveReason; }
  public void setArchiveReason(String archiveReason) { this.archiveReason = archiveReason; }

  public String getPrimaryCategoryId() { return primaryCategoryId; }
  public void setPrimaryCategoryId(String primaryCategoryId) { this.primaryCategoryId = primaryCategoryId; }

  public String getSubcategoryId() { return subcategoryId; }
  public void setSubcategoryId(String subcategoryId) { this.subcategoryId = subcategoryId; }

  public String getServiceTier() { return serviceTier; }
  public void setServiceTier(String serviceTier) { this.serviceTier = serviceTier; }

  public String getTemplateTags() { return templateTags; }
  public void setTemplateTags(String templateTags) { this.templateTags = templateTags; }

  public String getConceptPack() { return conceptPack; }
  public void setConceptPack(String conceptPack) { this.conceptPack = conceptPack; }

  public String getRulesPack() { return rulesPack; }
  public void setRulesPack(String rulesPack) { this.rulesPack = rulesPack; }

  public String getBrandPack() { return brandPack; }
  public void setBrandPack(String brandPack) { this.brandPack = brandPack; }

  public String getParticipationPack() { return participationPack; }
  public void setParticipationPack(String participationPack) { this.participationPack = participationPack; }

  public String getOperationsPack() { return operationsPack; }
  public void setOperationsPack(String operationsPack) { this.operationsPack = operationsPack; }

  public String getLegalPack() { return legalPack; }
  public void setLegalPack(String legalPack) { this.legalPack = legalPack; }

  public String getLockMap() { return lockMap; }
  public void setLockMap(String lockMap) { this.lockMap = lockMap; }

  public String getTemplateRecommendationConfig() { return templateRecommendationConfig; }
  public void setTemplateRecommendationConfig(String templateRecommendationConfig) { this.templateRecommendationConfig = templateRecommendationConfig; }

  public String getTemplateAuditLog() { return templateAuditLog; }
  public void setTemplateAuditLog(String templateAuditLog) { this.templateAuditLog = templateAuditLog; }

  public String getTemplateId() { return templateId; }
  public void setTemplateId(String templateId) { this.templateId = templateId; }

  public String getTemplateFamilyIdSnapshot() { return templateFamilyIdSnapshot; }
  public void setTemplateFamilyIdSnapshot(String templateFamilyIdSnapshot) { this.templateFamilyIdSnapshot = templateFamilyIdSnapshot; }

  public Double getTemplateVersionNumberSnapshot() { return templateVersionNumberSnapshot; }
  public void setTemplateVersionNumberSnapshot(Double templateVersionNumberSnapshot) { this.templateVersionNumberSnapshot = templateVersionNumberSnapshot; }

  public String getTemplateVersionSnapshot() { return templateVersionSnapshot; }
  public void setTemplateVersionSnapshot(String templateVersionSnapshot) { this.templateVersionSnapshot = templateVersionSnapshot; }

  public Instant getTemplateSnapshotCreatedAt() { return templateSnapshotCreatedAt; }
  public void setTemplateSnapshotCreatedAt(Instant templateSnapshotCreatedAt) { this.templateSnapshotCreatedAt = templateSnapshotCreatedAt; }

  public String getHostBrandOverrides() { return hostBrandOverrides; }
  public void setHostBrandOverrides(String hostBrandOverrides) { this.hostBrandOverrides = hostBrandOverrides; }

  public String getAdminBrandAdjustments() { return adminBrandAdjustments; }
  public void setAdminBrandAdjustments(String adminBrandAdjustments) { this.adminBrandAdjustments = adminBrandAdjustments; }

  public String getApprovedBrandPack() { return approvedBrandPack; }
  public void setApprovedBrandPack(String approvedBrandPack) { this.approvedBrandPack = approvedBrandPack; }

  public String getApprovedBy() { return approvedBy; }
  public void setApprovedBy(String approvedBy) { this.approvedBy = approvedBy; }

  public Instant getApprovedAt() { return approvedAt; }
  public void setApprovedAt(Instant approvedAt) { this.approvedAt = approvedAt; }

  public Boolean getApprovalLocked() { return approvalLocked; }
  public void setApprovalLocked(Boolean approvalLocked) { this.approvalLocked = approvalLocked; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
