package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge_category` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge_category")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeCategoryEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "slug", length = 255)
  private String slug;

  @Column(name = "category_id", length = 255)
  private String categoryId;

  @Column(name = "icon", length = 255)
  private String icon;

  @Column(name = "tagline", length = 255)
  private String tagline;

  @Column(name = "short_description", columnDefinition = "LONGTEXT")
  private String shortDescription;

  @Column(name = "full_description", columnDefinition = "LONGTEXT")
  private String fullDescription;

  @Column(name = "hero_image", length = 1024)
  private String heroImage;

  @Column(name = "hero_video", length = 255)
  private String heroVideo;

  @Column(name = "theme_colour", length = 255)
  private String themeColour;

  @Column(name = "secondary_colour", length = 255)
  private String secondaryColour;

  @Column(name = "work_types", columnDefinition = "LONGTEXT")
  private String workTypes;

  @Column(name = "learning_outcomes", columnDefinition = "LONGTEXT")
  private String learningOutcomes;

  @Column(name = "benefits", columnDefinition = "LONGTEXT")
  private String benefits;

  @Column(name = "audience_types", columnDefinition = "LONGTEXT")
  private String audienceTypes;

  @Column(name = "eligibility_guidance", length = 255)
  private String eligibilityGuidance;

  @Column(name = "challenge_formats", columnDefinition = "LONGTEXT")
  private String challengeFormats;

  @Column(name = "gallery_images", columnDefinition = "LONGTEXT")
  private String galleryImages;

  @Column(name = "faq_items", columnDefinition = "LONGTEXT")
  private String faqItems;

  @Column(name = "seo_title", length = 255)
  private String seoTitle;

  @Column(name = "seo_description", columnDefinition = "LONGTEXT")
  private String seoDescription;

  @Column(name = "social_image", length = 1024)
  private String socialImage;

  @Column(name = "display_order")
  private Double displayOrder;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getSlug() { return slug; }
  public void setSlug(String slug) { this.slug = slug; }

  public String getCategoryId() { return categoryId; }
  public void setCategoryId(String categoryId) { this.categoryId = categoryId; }

  public String getIcon() { return icon; }
  public void setIcon(String icon) { this.icon = icon; }

  public String getTagline() { return tagline; }
  public void setTagline(String tagline) { this.tagline = tagline; }

  public String getShortDescription() { return shortDescription; }
  public void setShortDescription(String shortDescription) { this.shortDescription = shortDescription; }

  public String getFullDescription() { return fullDescription; }
  public void setFullDescription(String fullDescription) { this.fullDescription = fullDescription; }

  public String getHeroImage() { return heroImage; }
  public void setHeroImage(String heroImage) { this.heroImage = heroImage; }

  public String getHeroVideo() { return heroVideo; }
  public void setHeroVideo(String heroVideo) { this.heroVideo = heroVideo; }

  public String getThemeColour() { return themeColour; }
  public void setThemeColour(String themeColour) { this.themeColour = themeColour; }

  public String getSecondaryColour() { return secondaryColour; }
  public void setSecondaryColour(String secondaryColour) { this.secondaryColour = secondaryColour; }

  public String getWorkTypes() { return workTypes; }
  public void setWorkTypes(String workTypes) { this.workTypes = workTypes; }

  public String getLearningOutcomes() { return learningOutcomes; }
  public void setLearningOutcomes(String learningOutcomes) { this.learningOutcomes = learningOutcomes; }

  public String getBenefits() { return benefits; }
  public void setBenefits(String benefits) { this.benefits = benefits; }

  public String getAudienceTypes() { return audienceTypes; }
  public void setAudienceTypes(String audienceTypes) { this.audienceTypes = audienceTypes; }

  public String getEligibilityGuidance() { return eligibilityGuidance; }
  public void setEligibilityGuidance(String eligibilityGuidance) { this.eligibilityGuidance = eligibilityGuidance; }

  public String getChallengeFormats() { return challengeFormats; }
  public void setChallengeFormats(String challengeFormats) { this.challengeFormats = challengeFormats; }

  public String getGalleryImages() { return galleryImages; }
  public void setGalleryImages(String galleryImages) { this.galleryImages = galleryImages; }

  public String getFaqItems() { return faqItems; }
  public void setFaqItems(String faqItems) { this.faqItems = faqItems; }

  public String getSeoTitle() { return seoTitle; }
  public void setSeoTitle(String seoTitle) { this.seoTitle = seoTitle; }

  public String getSeoDescription() { return seoDescription; }
  public void setSeoDescription(String seoDescription) { this.seoDescription = seoDescription; }

  public String getSocialImage() { return socialImage; }
  public void setSocialImage(String socialImage) { this.socialImage = socialImage; }

  public Double getDisplayOrder() { return displayOrder; }
  public void setDisplayOrder(Double displayOrder) { this.displayOrder = displayOrder; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
