package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `challenge_rights_configuration` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "challenge_rights_configuration")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChallengeRightsConfigurationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "included_scope_versions", columnDefinition = "LONGTEXT")
  private String includedScopeVersions;

  @Column(name = "music_policy", length = 64)
  private String musicPolicy;

  @Column(name = "third_party_policy", length = 64)
  private String thirdPartyPolicy;

  @Column(name = "sponsor_use_period", length = 255)
  private String sponsorUsePeriod;

  @Column(name = "marketing_contact_senders", columnDefinition = "LONGTEXT")
  private String marketingContactSenders;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getIncludedScopeVersions() { return includedScopeVersions; }
  public void setIncludedScopeVersions(String includedScopeVersions) { this.includedScopeVersions = includedScopeVersions; }

  public String getMusicPolicy() { return musicPolicy; }
  public void setMusicPolicy(String musicPolicy) { this.musicPolicy = musicPolicy; }

  public String getThirdPartyPolicy() { return thirdPartyPolicy; }
  public void setThirdPartyPolicy(String thirdPartyPolicy) { this.thirdPartyPolicy = thirdPartyPolicy; }

  public String getSponsorUsePeriod() { return sponsorUsePeriod; }
  public void setSponsorUsePeriod(String sponsorUsePeriod) { this.sponsorUsePeriod = sponsorUsePeriod; }

  public String getMarketingContactSenders() { return marketingContactSenders; }
  public void setMarketingContactSenders(String marketingContactSenders) { this.marketingContactSenders = marketingContactSenders; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
