package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `combined_result` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "combined_result")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CombinedResultEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "panel_id", length = 255)
  private String panelId;

  @Column(name = "entry_title", length = 255)
  private String entryTitle;

  @Column(name = "creator_name", length = 255)
  private String creatorName;

  @Column(name = "judge_score")
  private Double judgeScore;

  @Column(name = "public_score")
  private Double publicScore;

  @Column(name = "combined_score")
  private Double combinedScore;

  @Column(name = "combined_rank")
  private Double combinedRank;

  @Column(name = "public_votes")
  private Double publicVotes;

  @Column(name = "judge_count")
  private Double judgeCount;

  @Column(name = "computed_at")
  private Instant computedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getPanelId() { return panelId; }
  public void setPanelId(String panelId) { this.panelId = panelId; }

  public String getEntryTitle() { return entryTitle; }
  public void setEntryTitle(String entryTitle) { this.entryTitle = entryTitle; }

  public String getCreatorName() { return creatorName; }
  public void setCreatorName(String creatorName) { this.creatorName = creatorName; }

  public Double getJudgeScore() { return judgeScore; }
  public void setJudgeScore(Double judgeScore) { this.judgeScore = judgeScore; }

  public Double getPublicScore() { return publicScore; }
  public void setPublicScore(Double publicScore) { this.publicScore = publicScore; }

  public Double getCombinedScore() { return combinedScore; }
  public void setCombinedScore(Double combinedScore) { this.combinedScore = combinedScore; }

  public Double getCombinedRank() { return combinedRank; }
  public void setCombinedRank(Double combinedRank) { this.combinedRank = combinedRank; }

  public Double getPublicVotes() { return publicVotes; }
  public void setPublicVotes(Double publicVotes) { this.publicVotes = publicVotes; }

  public Double getJudgeCount() { return judgeCount; }
  public void setJudgeCount(Double judgeCount) { this.judgeCount = judgeCount; }

  public Instant getComputedAt() { return computedAt; }
  public void setComputedAt(Instant computedAt) { this.computedAt = computedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
