package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `compliance_trigger` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "compliance_trigger")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ComplianceTriggerEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "code", length = 255)
  private String code;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "detection_source", length = 64)
  private String detectionSource;

  @Column(name = "detection_definition", columnDefinition = "LONGTEXT")
  private String detectionDefinition;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getCode() { return code; }
  public void setCode(String code) { this.code = code; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getDetectionSource() { return detectionSource; }
  public void setDetectionSource(String detectionSource) { this.detectionSource = detectionSource; }

  public String getDetectionDefinition() { return detectionDefinition; }
  public void setDetectionDefinition(String detectionDefinition) { this.detectionDefinition = detectionDefinition; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
