package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `compliance_assessment_finding` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "compliance_assessment_finding")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ComplianceAssessmentFindingEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "assessment_id", length = 255)
  private String assessmentId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "rule_version_id", length = 255)
  private String ruleVersionId;

  @Column(name = "rule_code", length = 255)
  private String ruleCode;

  @Column(name = "obligation_type", length = 255)
  private String obligationType;

  @Column(name = "jurisdiction_code", length = 1024)
  private String jurisdictionCode;

  @Column(name = "gate", length = 64)
  private String gate;

  @Column(name = "blocking")
  private Boolean blocking;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "waiver_reason", columnDefinition = "LONGTEXT")
  private String waiverReason;

  @Column(name = "waived_by", length = 255)
  private String waivedBy;

  @Column(name = "waived_at")
  private Instant waivedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getAssessmentId() { return assessmentId; }
  public void setAssessmentId(String assessmentId) { this.assessmentId = assessmentId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getRuleVersionId() { return ruleVersionId; }
  public void setRuleVersionId(String ruleVersionId) { this.ruleVersionId = ruleVersionId; }

  public String getRuleCode() { return ruleCode; }
  public void setRuleCode(String ruleCode) { this.ruleCode = ruleCode; }

  public String getObligationType() { return obligationType; }
  public void setObligationType(String obligationType) { this.obligationType = obligationType; }

  public String getJurisdictionCode() { return jurisdictionCode; }
  public void setJurisdictionCode(String jurisdictionCode) { this.jurisdictionCode = jurisdictionCode; }

  public String getGate() { return gate; }
  public void setGate(String gate) { this.gate = gate; }

  public Boolean getBlocking() { return blocking; }
  public void setBlocking(Boolean blocking) { this.blocking = blocking; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getWaiverReason() { return waiverReason; }
  public void setWaiverReason(String waiverReason) { this.waiverReason = waiverReason; }

  public String getWaivedBy() { return waivedBy; }
  public void setWaivedBy(String waivedBy) { this.waivedBy = waivedBy; }

  public Instant getWaivedAt() { return waivedAt; }
  public void setWaivedAt(Instant waivedAt) { this.waivedAt = waivedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
