package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `compliance_gate` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "compliance_gate")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ComplianceGateEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "legal_review_status", length = 64)
  private String legalReviewStatus;

  @Column(name = "promoter_confirmed")
  private Boolean promoterConfirmed;

  @Column(name = "terms_approved")
  private Boolean termsApproved;

  @Column(name = "minor_participation_reviewed")
  private Boolean minorParticipationReviewed;

  @Column(name = "voting_reviewed")
  private Boolean votingReviewed;

  @Column(name = "permit_position_recorded")
  private Boolean permitPositionRecorded;

  @Column(name = "prize_funding_confirmed")
  private Boolean prizeFundingConfirmed;

  @Column(name = "launch_blocked")
  private Boolean launchBlocked;

  @Column(name = "legal_review_reference", length = 255)
  private String legalReviewReference;

  @Column(name = "gate_notes", columnDefinition = "LONGTEXT")
  private String gateNotes;

  @Column(name = "grandfathered_live")
  private Boolean grandfatheredLive;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getLegalReviewStatus() { return legalReviewStatus; }
  public void setLegalReviewStatus(String legalReviewStatus) { this.legalReviewStatus = legalReviewStatus; }

  public Boolean getPromoterConfirmed() { return promoterConfirmed; }
  public void setPromoterConfirmed(Boolean promoterConfirmed) { this.promoterConfirmed = promoterConfirmed; }

  public Boolean getTermsApproved() { return termsApproved; }
  public void setTermsApproved(Boolean termsApproved) { this.termsApproved = termsApproved; }

  public Boolean getMinorParticipationReviewed() { return minorParticipationReviewed; }
  public void setMinorParticipationReviewed(Boolean minorParticipationReviewed) { this.minorParticipationReviewed = minorParticipationReviewed; }

  public Boolean getVotingReviewed() { return votingReviewed; }
  public void setVotingReviewed(Boolean votingReviewed) { this.votingReviewed = votingReviewed; }

  public Boolean getPermitPositionRecorded() { return permitPositionRecorded; }
  public void setPermitPositionRecorded(Boolean permitPositionRecorded) { this.permitPositionRecorded = permitPositionRecorded; }

  public Boolean getPrizeFundingConfirmed() { return prizeFundingConfirmed; }
  public void setPrizeFundingConfirmed(Boolean prizeFundingConfirmed) { this.prizeFundingConfirmed = prizeFundingConfirmed; }

  public Boolean getLaunchBlocked() { return launchBlocked; }
  public void setLaunchBlocked(Boolean launchBlocked) { this.launchBlocked = launchBlocked; }

  public String getLegalReviewReference() { return legalReviewReference; }
  public void setLegalReviewReference(String legalReviewReference) { this.legalReviewReference = legalReviewReference; }

  public String getGateNotes() { return gateNotes; }
  public void setGateNotes(String gateNotes) { this.gateNotes = gateNotes; }

  public Boolean getGrandfatheredLive() { return grandfatheredLive; }
  public void setGrandfatheredLive(Boolean grandfatheredLive) { this.grandfatheredLive = grandfatheredLive; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
