package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `compliance_audit_event` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "compliance_audit_event")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ComplianceAuditEventEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "event_type", length = 64)
  private String eventType;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "assessment_id", length = 255)
  private String assessmentId;

  @Column(name = "finding_id", length = 255)
  private String findingId;

  @Column(name = "actor_id", length = 255)
  private String actorId;

  @Column(name = "actor_email", length = 255)
  private String actorEmail;

  @Column(name = "detail", columnDefinition = "LONGTEXT")
  private String detail;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getEventType() { return eventType; }
  public void setEventType(String eventType) { this.eventType = eventType; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getAssessmentId() { return assessmentId; }
  public void setAssessmentId(String assessmentId) { this.assessmentId = assessmentId; }

  public String getFindingId() { return findingId; }
  public void setFindingId(String findingId) { this.findingId = findingId; }

  public String getActorId() { return actorId; }
  public void setActorId(String actorId) { this.actorId = actorId; }

  public String getActorEmail() { return actorEmail; }
  public void setActorEmail(String actorEmail) { this.actorEmail = actorEmail; }

  public String getDetail() { return detail; }
  public void setDetail(String detail) { this.detail = detail; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
