package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `competition_assignment` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "competition_assignment")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CompetitionAssignmentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "competition_title", length = 255)
  private String competitionTitle;

  @Column(name = "judge_profile_id", length = 1024)
  private String judgeProfileId;

  @Column(name = "judge_name", length = 255)
  private String judgeName;

  @Column(name = "judge_email", length = 255)
  private String judgeEmail;

  @Column(name = "role", length = 64)
  private String role;

  @Column(name = "assigned_at")
  private Instant assignedAt;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getCompetitionTitle() { return competitionTitle; }
  public void setCompetitionTitle(String competitionTitle) { this.competitionTitle = competitionTitle; }

  public String getJudgeProfileId() { return judgeProfileId; }
  public void setJudgeProfileId(String judgeProfileId) { this.judgeProfileId = judgeProfileId; }

  public String getJudgeName() { return judgeName; }
  public void setJudgeName(String judgeName) { this.judgeName = judgeName; }

  public String getJudgeEmail() { return judgeEmail; }
  public void setJudgeEmail(String judgeEmail) { this.judgeEmail = judgeEmail; }

  public String getRole() { return role; }
  public void setRole(String role) { this.role = role; }

  public Instant getAssignedAt() { return assignedAt; }
  public void setAssignedAt(Instant assignedAt) { this.assignedAt = assignedAt; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
