package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `compliance_gate_log` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "compliance_gate_log")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ComplianceGateLogEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "gate_id", length = 255)
  private String gateId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "action", length = 64)
  private String action;

  @Column(name = "field_name", length = 255)
  private String fieldName;

  @Column(name = "old_value", length = 255)
  private String oldValue;

  @Column(name = "new_value", length = 255)
  private String newValue;

  @Column(name = "changed_by_id", length = 255)
  private String changedById;

  @Column(name = "changed_by_email", length = 255)
  private String changedByEmail;

  @Column(name = "note", columnDefinition = "LONGTEXT")
  private String note;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getGateId() { return gateId; }
  public void setGateId(String gateId) { this.gateId = gateId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getAction() { return action; }
  public void setAction(String action) { this.action = action; }

  public String getFieldName() { return fieldName; }
  public void setFieldName(String fieldName) { this.fieldName = fieldName; }

  public String getOldValue() { return oldValue; }
  public void setOldValue(String oldValue) { this.oldValue = oldValue; }

  public String getNewValue() { return newValue; }
  public void setNewValue(String newValue) { this.newValue = newValue; }

  public String getChangedById() { return changedById; }
  public void setChangedById(String changedById) { this.changedById = changedById; }

  public String getChangedByEmail() { return changedByEmail; }
  public void setChangedByEmail(String changedByEmail) { this.changedByEmail = changedByEmail; }

  public String getNote() { return note; }
  public void setNote(String note) { this.note = note; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
