package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `consent_requirement` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "consent_requirement")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ConsentRequirementEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "method", length = 64)
  private String method;

  @Column(name = "clause_reference", length = 255)
  private String clauseReference;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "is_active")
  private Boolean isActive;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getMethod() { return method; }
  public void setMethod(String method) { this.method = method; }

  public String getClauseReference() { return clauseReference; }
  public void setClauseReference(String clauseReference) { this.clauseReference = clauseReference; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public Boolean getIsActive() { return isActive; }
  public void setIsActive(Boolean isActive) { this.isActive = isActive; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
