package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `creator` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "creator")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class CreatorEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "city", length = 255)
  private String city;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "tag", length = 255)
  private String tag;

  @Column(name = "role", length = 255)
  private String role;

  @Column(name = "quote", length = 255)
  private String quote;

  @Column(name = "icon", length = 255)
  private String icon;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getCity() { return city; }
  public void setCity(String city) { this.city = city; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getTag() { return tag; }
  public void setTag(String tag) { this.tag = tag; }

  public String getRole() { return role; }
  public void setRole(String role) { this.role = role; }

  public String getQuote() { return quote; }
  public void setQuote(String quote) { this.quote = quote; }

  public String getIcon() { return icon; }
  public void setIcon(String icon) { this.icon = icon; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
