package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `email_verification` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "email_verification")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class EmailVerificationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "email", length = 255)
  private String email;

  @Column(name = "purpose", length = 255)
  private String purpose;

  @Column(name = "code", length = 255)
  private String code;

  @Column(name = "token", length = 255)
  private String token;

  @Column(name = "expires_at")
  private Instant expiresAt;

  @Column(name = "attempts")
  private Double attempts;

  @Column(name = "verified")
  private Boolean verified;

  @Column(name = "verified_at")
  private Instant verifiedAt;

  @Column(name = "consumed")
  private Boolean consumed;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getEmail() { return email; }
  public void setEmail(String email) { this.email = email; }

  public String getPurpose() { return purpose; }
  public void setPurpose(String purpose) { this.purpose = purpose; }

  public String getCode() { return code; }
  public void setCode(String code) { this.code = code; }

  public String getToken() { return token; }
  public void setToken(String token) { this.token = token; }

  public Instant getExpiresAt() { return expiresAt; }
  public void setExpiresAt(Instant expiresAt) { this.expiresAt = expiresAt; }

  public Double getAttempts() { return attempts; }
  public void setAttempts(Double attempts) { this.attempts = attempts; }

  public Boolean getVerified() { return verified; }
  public void setVerified(Boolean verified) { this.verified = verified; }

  public Instant getVerifiedAt() { return verifiedAt; }
  public void setVerifiedAt(Instant verifiedAt) { this.verifiedAt = verifiedAt; }

  public Boolean getConsumed() { return consumed; }
  public void setConsumed(Boolean consumed) { this.consumed = consumed; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
