package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `email_campaign` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "email_campaign")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class EmailCampaignEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "type", length = 64)
  private String type;

  @Column(name = "audience_types", columnDefinition = "LONGTEXT")
  private String audienceTypes;

  @Column(name = "states", columnDefinition = "LONGTEXT")
  private String states;

  @Column(name = "categories", columnDefinition = "LONGTEXT")
  private String categories;

  @Column(name = "participated_only")
  private Boolean participatedOnly;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "subject", length = 255)
  private String subject;

  @Column(name = "body", columnDefinition = "LONGTEXT")
  private String body;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "audience_count")
  private Double audienceCount;

  @Column(name = "sent_count")
  private Double sentCount;

  @Column(name = "skipped_unregistered")
  private Double skippedUnregistered;

  @Column(name = "sent_at")
  private Instant sentAt;

  @Column(name = "created_by", length = 255)
  private String createdBy;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getType() { return type; }
  public void setType(String type) { this.type = type; }

  public String getAudienceTypes() { return audienceTypes; }
  public void setAudienceTypes(String audienceTypes) { this.audienceTypes = audienceTypes; }

  public String getStates() { return states; }
  public void setStates(String states) { this.states = states; }

  public String getCategories() { return categories; }
  public void setCategories(String categories) { this.categories = categories; }

  public Boolean getParticipatedOnly() { return participatedOnly; }
  public void setParticipatedOnly(Boolean participatedOnly) { this.participatedOnly = participatedOnly; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getSubject() { return subject; }
  public void setSubject(String subject) { this.subject = subject; }

  public String getBody() { return body; }
  public void setBody(String body) { this.body = body; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Double getAudienceCount() { return audienceCount; }
  public void setAudienceCount(Double audienceCount) { this.audienceCount = audienceCount; }

  public Double getSentCount() { return sentCount; }
  public void setSentCount(Double sentCount) { this.sentCount = sentCount; }

  public Double getSkippedUnregistered() { return skippedUnregistered; }
  public void setSkippedUnregistered(Double skippedUnregistered) { this.skippedUnregistered = skippedUnregistered; }

  public Instant getSentAt() { return sentAt; }
  public void setSentAt(Instant sentAt) { this.sentAt = sentAt; }

  public String getCreatedBy() { return createdBy; }
  public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
