package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `enterprise_quote` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "enterprise_quote")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class EnterpriseQuoteEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "draft_id", length = 255)
  private String draftId;

  @Column(name = "line_items", columnDefinition = "LONGTEXT")
  private String lineItems;

  @Column(name = "packaged_floor")
  private Double packagedFloor;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "account_manager", length = 255)
  private String accountManager;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getDraftId() { return draftId; }
  public void setDraftId(String draftId) { this.draftId = draftId; }

  public String getLineItems() { return lineItems; }
  public void setLineItems(String lineItems) { this.lineItems = lineItems; }

  public Double getPackagedFloor() { return packagedFloor; }
  public void setPackagedFloor(Double packagedFloor) { this.packagedFloor = packagedFloor; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getAccountManager() { return accountManager; }
  public void setAccountManager(String accountManager) { this.accountManager = accountManager; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
