package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `entry_judge_assignment` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "entry_judge_assignment")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class EntryJudgeAssignmentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "panel_id", length = 255)
  private String panelId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "anonymous_id", length = 255)
  private String anonymousId;

  @Column(name = "judge_profile_id", length = 1024)
  private String judgeProfileId;

  @Column(name = "judge_name", length = 255)
  private String judgeName;

  @Column(name = "blind_work_type", length = 255)
  private String blindWorkType;

  @Column(name = "blind_work_text", columnDefinition = "LONGTEXT")
  private String blindWorkText;

  @Column(name = "blind_work_link", length = 1024)
  private String blindWorkLink;

  @Column(name = "assigned_at")
  private Instant assignedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPanelId() { return panelId; }
  public void setPanelId(String panelId) { this.panelId = panelId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getAnonymousId() { return anonymousId; }
  public void setAnonymousId(String anonymousId) { this.anonymousId = anonymousId; }

  public String getJudgeProfileId() { return judgeProfileId; }
  public void setJudgeProfileId(String judgeProfileId) { this.judgeProfileId = judgeProfileId; }

  public String getJudgeName() { return judgeName; }
  public void setJudgeName(String judgeName) { this.judgeName = judgeName; }

  public String getBlindWorkType() { return blindWorkType; }
  public void setBlindWorkType(String blindWorkType) { this.blindWorkType = blindWorkType; }

  public String getBlindWorkText() { return blindWorkText; }
  public void setBlindWorkText(String blindWorkText) { this.blindWorkText = blindWorkText; }

  public String getBlindWorkLink() { return blindWorkLink; }
  public void setBlindWorkLink(String blindWorkLink) { this.blindWorkLink = blindWorkLink; }

  public Instant getAssignedAt() { return assignedAt; }
  public void setAssignedAt(Instant assignedAt) { this.assignedAt = assignedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
