package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `entry` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "entry")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class EntryEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "title", length = 255)
  private String title;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "creator_name", length = 255)
  private String creatorName;

  @Column(name = "creator_email", length = 255)
  private String creatorEmail;

  @Column(name = "creator_email_masked", length = 255)
  private String creatorEmailMasked;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "city", length = 255)
  private String city;

  @Column(name = "division", length = 64)
  private String division;

  @Column(name = "work_type", length = 64)
  private String workType;

  @Column(name = "work_text", columnDefinition = "LONGTEXT")
  private String workText;

  @Column(name = "work_link", length = 1024)
  private String workLink;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "review_note", columnDefinition = "LONGTEXT")
  private String reviewNote;

  @Column(name = "reviewer_id", length = 255)
  private String reviewerId;

  @Column(name = "reviewer_email", length = 255)
  private String reviewerEmail;

  @Column(name = "reviewed_at")
  private Instant reviewedAt;

  @Column(name = "moderated_at")
  private Instant moderatedAt;

  @Column(name = "moderation_batch_id", length = 255)
  private String moderationBatchId;

  @Column(name = "is_minor")
  private Boolean isMinor;

  @Column(name = "is_winner")
  private Boolean isWinner;

  @Column(name = "is_finalist")
  private Boolean isFinalist;

  @Column(name = "finalist_week", length = 255)
  private String finalistWeek;

  @Column(name = "upstream_entry_id", length = 255)
  private String upstreamEntryId;

  @Column(name = "source", length = 64)
  private String source;

  @Column(name = "category", length = 255)
  private String category;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "submitted_at")
  private Instant submittedAt;

  @Column(name = "vote_count")
  private Double voteCount;

  @Column(name = "terms_accepted_at")
  private Instant termsAcceptedAt;

  @Column(name = "terms_document_id", columnDefinition = "LONGTEXT")
  private String termsDocumentId;

  @Column(name = "consent_status", length = 64)
  private String consentStatus;

  @Column(name = "guardian_approval_status", length = 64)
  private String guardianApprovalStatus;

  @Column(name = "guardian_id", length = 255)
  private String guardianId;

  @Column(name = "guardian_name", length = 255)
  private String guardianName;

  @Column(name = "guardian_relationship", length = 255)
  private String guardianRelationship;

  @Column(name = "guardian_email", length = 255)
  private String guardianEmail;

  @Column(name = "guardian_mobile", length = 255)
  private String guardianMobile;

  @Column(name = "guardian_address", length = 255)
  private String guardianAddress;

  @Column(name = "approval_timestamp")
  private Instant approvalTimestamp;

  @Column(name = "decline_reason", columnDefinition = "LONGTEXT")
  private String declineReason;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getTitle() { return title; }
  public void setTitle(String title) { this.title = title; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public String getCreatorName() { return creatorName; }
  public void setCreatorName(String creatorName) { this.creatorName = creatorName; }

  public String getCreatorEmail() { return creatorEmail; }
  public void setCreatorEmail(String creatorEmail) { this.creatorEmail = creatorEmail; }

  public String getCreatorEmailMasked() { return creatorEmailMasked; }
  public void setCreatorEmailMasked(String creatorEmailMasked) { this.creatorEmailMasked = creatorEmailMasked; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getCity() { return city; }
  public void setCity(String city) { this.city = city; }

  public String getDivision() { return division; }
  public void setDivision(String division) { this.division = division; }

  public String getWorkType() { return workType; }
  public void setWorkType(String workType) { this.workType = workType; }

  public String getWorkText() { return workText; }
  public void setWorkText(String workText) { this.workText = workText; }

  public String getWorkLink() { return workLink; }
  public void setWorkLink(String workLink) { this.workLink = workLink; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getReviewNote() { return reviewNote; }
  public void setReviewNote(String reviewNote) { this.reviewNote = reviewNote; }

  public String getReviewerId() { return reviewerId; }
  public void setReviewerId(String reviewerId) { this.reviewerId = reviewerId; }

  public String getReviewerEmail() { return reviewerEmail; }
  public void setReviewerEmail(String reviewerEmail) { this.reviewerEmail = reviewerEmail; }

  public Instant getReviewedAt() { return reviewedAt; }
  public void setReviewedAt(Instant reviewedAt) { this.reviewedAt = reviewedAt; }

  public Instant getModeratedAt() { return moderatedAt; }
  public void setModeratedAt(Instant moderatedAt) { this.moderatedAt = moderatedAt; }

  public String getModerationBatchId() { return moderationBatchId; }
  public void setModerationBatchId(String moderationBatchId) { this.moderationBatchId = moderationBatchId; }

  public Boolean getIsMinor() { return isMinor; }
  public void setIsMinor(Boolean isMinor) { this.isMinor = isMinor; }

  public Boolean getIsWinner() { return isWinner; }
  public void setIsWinner(Boolean isWinner) { this.isWinner = isWinner; }

  public Boolean getIsFinalist() { return isFinalist; }
  public void setIsFinalist(Boolean isFinalist) { this.isFinalist = isFinalist; }

  public String getFinalistWeek() { return finalistWeek; }
  public void setFinalistWeek(String finalistWeek) { this.finalistWeek = finalistWeek; }

  public String getUpstreamEntryId() { return upstreamEntryId; }
  public void setUpstreamEntryId(String upstreamEntryId) { this.upstreamEntryId = upstreamEntryId; }

  public String getSource() { return source; }
  public void setSource(String source) { this.source = source; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public Instant getSubmittedAt() { return submittedAt; }
  public void setSubmittedAt(Instant submittedAt) { this.submittedAt = submittedAt; }

  public Double getVoteCount() { return voteCount; }
  public void setVoteCount(Double voteCount) { this.voteCount = voteCount; }

  public Instant getTermsAcceptedAt() { return termsAcceptedAt; }
  public void setTermsAcceptedAt(Instant termsAcceptedAt) { this.termsAcceptedAt = termsAcceptedAt; }

  public String getTermsDocumentId() { return termsDocumentId; }
  public void setTermsDocumentId(String termsDocumentId) { this.termsDocumentId = termsDocumentId; }

  public String getConsentStatus() { return consentStatus; }
  public void setConsentStatus(String consentStatus) { this.consentStatus = consentStatus; }

  public String getGuardianApprovalStatus() { return guardianApprovalStatus; }
  public void setGuardianApprovalStatus(String guardianApprovalStatus) { this.guardianApprovalStatus = guardianApprovalStatus; }

  public String getGuardianId() { return guardianId; }
  public void setGuardianId(String guardianId) { this.guardianId = guardianId; }

  public String getGuardianName() { return guardianName; }
  public void setGuardianName(String guardianName) { this.guardianName = guardianName; }

  public String getGuardianRelationship() { return guardianRelationship; }
  public void setGuardianRelationship(String guardianRelationship) { this.guardianRelationship = guardianRelationship; }

  public String getGuardianEmail() { return guardianEmail; }
  public void setGuardianEmail(String guardianEmail) { this.guardianEmail = guardianEmail; }

  public String getGuardianMobile() { return guardianMobile; }
  public void setGuardianMobile(String guardianMobile) { this.guardianMobile = guardianMobile; }

  public String getGuardianAddress() { return guardianAddress; }
  public void setGuardianAddress(String guardianAddress) { this.guardianAddress = guardianAddress; }

  public Instant getApprovalTimestamp() { return approvalTimestamp; }
  public void setApprovalTimestamp(Instant approvalTimestamp) { this.approvalTimestamp = approvalTimestamp; }

  public String getDeclineReason() { return declineReason; }
  public void setDeclineReason(String declineReason) { this.declineReason = declineReason; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
