package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `gate_check` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "gate_check")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class GateCheckEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "gate_code", length = 64)
  private String gateCode;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "passed_at")
  private Instant passedAt;

  @Column(name = "passed_by_id", length = 255)
  private String passedById;

  @Column(name = "passed_by_email", length = 255)
  private String passedByEmail;

  @Column(name = "grandfathered")
  private Boolean grandfathered;

  @Column(name = "relocked_reason", columnDefinition = "LONGTEXT")
  private String relockedReason;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getGateCode() { return gateCode; }
  public void setGateCode(String gateCode) { this.gateCode = gateCode; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getPassedAt() { return passedAt; }
  public void setPassedAt(Instant passedAt) { this.passedAt = passedAt; }

  public String getPassedById() { return passedById; }
  public void setPassedById(String passedById) { this.passedById = passedById; }

  public String getPassedByEmail() { return passedByEmail; }
  public void setPassedByEmail(String passedByEmail) { this.passedByEmail = passedByEmail; }

  public Boolean getGrandfathered() { return grandfathered; }
  public void setGrandfathered(Boolean grandfathered) { this.grandfathered = grandfathered; }

  public String getRelockedReason() { return relockedReason; }
  public void setRelockedReason(String relockedReason) { this.relockedReason = relockedReason; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
