package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `guardian_consent` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "guardian_consent")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class GuardianConsentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "participant_name", length = 255)
  private String participantName;

  @Column(name = "participant_email", length = 255)
  private String participantEmail;

  @Column(name = "requirement_id", length = 255)
  private String requirementId;

  @Column(name = "requirement_version")
  private Double requirementVersion;

  @Column(name = "guardian_name", length = 255)
  private String guardianName;

  @Column(name = "guardian_relationship", length = 255)
  private String guardianRelationship;

  @Column(name = "guardian_contact", length = 255)
  private String guardianContact;

  @Column(name = "method_used", length = 64)
  private String methodUsed;

  @Column(name = "verified_at")
  private Instant verifiedAt;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "withdrawn_at")
  private Instant withdrawnAt;

  @Column(name = "scopes_entering_challenge")
  private Boolean scopesEnteringChallenge;

  @Column(name = "scopes_terms_acceptance")
  private Boolean scopesTermsAcceptance;

  @Column(name = "scopes_personal_info_processing")
  private Boolean scopesPersonalInfoProcessing;

  @Column(name = "scopes_public_display_name")
  private Boolean scopesPublicDisplayName;

  @Column(name = "scopes_public_display_age_bracket")
  private Boolean scopesPublicDisplayAgeBracket;

  @Column(name = "scopes_publication_of_entry_media")
  private Boolean scopesPublicationOfEntryMedia;

  @Column(name = "scopes_promotional_reuse")
  private Boolean scopesPromotionalReuse;

  @Column(name = "scopes_direct_communication_with_minor")
  private Boolean scopesDirectCommunicationWithMinor;

  @Column(name = "scopes_public_voting_participation")
  private Boolean scopesPublicVotingParticipation;

  @Column(name = "scopes_prize_acceptance_payment")
  private Boolean scopesPrizeAcceptancePayment;

  @Column(name = "scopes_event_travel_attendance")
  private Boolean scopesEventTravelAttendance;

  @Column(name = "scopes_appears_in_entry")
  private Boolean scopesAppearsInEntry;

  @Column(name = "consent_wording_hash", length = 255)
  private String consentWordingHash;

  @Column(name = "withdrawal_reason", columnDefinition = "LONGTEXT")
  private String withdrawalReason;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getParticipantName() { return participantName; }
  public void setParticipantName(String participantName) { this.participantName = participantName; }

  public String getParticipantEmail() { return participantEmail; }
  public void setParticipantEmail(String participantEmail) { this.participantEmail = participantEmail; }

  public String getRequirementId() { return requirementId; }
  public void setRequirementId(String requirementId) { this.requirementId = requirementId; }

  public Double getRequirementVersion() { return requirementVersion; }
  public void setRequirementVersion(Double requirementVersion) { this.requirementVersion = requirementVersion; }

  public String getGuardianName() { return guardianName; }
  public void setGuardianName(String guardianName) { this.guardianName = guardianName; }

  public String getGuardianRelationship() { return guardianRelationship; }
  public void setGuardianRelationship(String guardianRelationship) { this.guardianRelationship = guardianRelationship; }

  public String getGuardianContact() { return guardianContact; }
  public void setGuardianContact(String guardianContact) { this.guardianContact = guardianContact; }

  public String getMethodUsed() { return methodUsed; }
  public void setMethodUsed(String methodUsed) { this.methodUsed = methodUsed; }

  public Instant getVerifiedAt() { return verifiedAt; }
  public void setVerifiedAt(Instant verifiedAt) { this.verifiedAt = verifiedAt; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getWithdrawnAt() { return withdrawnAt; }
  public void setWithdrawnAt(Instant withdrawnAt) { this.withdrawnAt = withdrawnAt; }

  public Boolean getScopesEnteringChallenge() { return scopesEnteringChallenge; }
  public void setScopesEnteringChallenge(Boolean scopesEnteringChallenge) { this.scopesEnteringChallenge = scopesEnteringChallenge; }

  public Boolean getScopesTermsAcceptance() { return scopesTermsAcceptance; }
  public void setScopesTermsAcceptance(Boolean scopesTermsAcceptance) { this.scopesTermsAcceptance = scopesTermsAcceptance; }

  public Boolean getScopesPersonalInfoProcessing() { return scopesPersonalInfoProcessing; }
  public void setScopesPersonalInfoProcessing(Boolean scopesPersonalInfoProcessing) { this.scopesPersonalInfoProcessing = scopesPersonalInfoProcessing; }

  public Boolean getScopesPublicDisplayName() { return scopesPublicDisplayName; }
  public void setScopesPublicDisplayName(Boolean scopesPublicDisplayName) { this.scopesPublicDisplayName = scopesPublicDisplayName; }

  public Boolean getScopesPublicDisplayAgeBracket() { return scopesPublicDisplayAgeBracket; }
  public void setScopesPublicDisplayAgeBracket(Boolean scopesPublicDisplayAgeBracket) { this.scopesPublicDisplayAgeBracket = scopesPublicDisplayAgeBracket; }

  public Boolean getScopesPublicationOfEntryMedia() { return scopesPublicationOfEntryMedia; }
  public void setScopesPublicationOfEntryMedia(Boolean scopesPublicationOfEntryMedia) { this.scopesPublicationOfEntryMedia = scopesPublicationOfEntryMedia; }

  public Boolean getScopesPromotionalReuse() { return scopesPromotionalReuse; }
  public void setScopesPromotionalReuse(Boolean scopesPromotionalReuse) { this.scopesPromotionalReuse = scopesPromotionalReuse; }

  public Boolean getScopesDirectCommunicationWithMinor() { return scopesDirectCommunicationWithMinor; }
  public void setScopesDirectCommunicationWithMinor(Boolean scopesDirectCommunicationWithMinor) { this.scopesDirectCommunicationWithMinor = scopesDirectCommunicationWithMinor; }

  public Boolean getScopesPublicVotingParticipation() { return scopesPublicVotingParticipation; }
  public void setScopesPublicVotingParticipation(Boolean scopesPublicVotingParticipation) { this.scopesPublicVotingParticipation = scopesPublicVotingParticipation; }

  public Boolean getScopesPrizeAcceptancePayment() { return scopesPrizeAcceptancePayment; }
  public void setScopesPrizeAcceptancePayment(Boolean scopesPrizeAcceptancePayment) { this.scopesPrizeAcceptancePayment = scopesPrizeAcceptancePayment; }

  public Boolean getScopesEventTravelAttendance() { return scopesEventTravelAttendance; }
  public void setScopesEventTravelAttendance(Boolean scopesEventTravelAttendance) { this.scopesEventTravelAttendance = scopesEventTravelAttendance; }

  public Boolean getScopesAppearsInEntry() { return scopesAppearsInEntry; }
  public void setScopesAppearsInEntry(Boolean scopesAppearsInEntry) { this.scopesAppearsInEntry = scopesAppearsInEntry; }

  public String getConsentWordingHash() { return consentWordingHash; }
  public void setConsentWordingHash(String consentWordingHash) { this.consentWordingHash = consentWordingHash; }

  public String getWithdrawalReason() { return withdrawalReason; }
  public void setWithdrawalReason(String withdrawalReason) { this.withdrawalReason = withdrawalReason; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
