package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `guardian_approval_request` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "guardian_approval_request")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class GuardianApprovalRequestEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "guardian_id", length = 255)
  private String guardianId;

  @Column(name = "guardian_email", length = 255)
  private String guardianEmail;

  @Column(name = "guardian_name", length = 255)
  private String guardianName;

  @Column(name = "child_name", length = 255)
  private String childName;

  @Column(name = "child_email", length = 255)
  private String childEmail;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "entry_title", length = 255)
  private String entryTitle;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "division", length = 255)
  private String division;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "decline_reason", columnDefinition = "LONGTEXT")
  private String declineReason;

  @Column(name = "decided_at")
  private Instant decidedAt;

  @Column(name = "notified_at")
  private Instant notifiedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getGuardianId() { return guardianId; }
  public void setGuardianId(String guardianId) { this.guardianId = guardianId; }

  public String getGuardianEmail() { return guardianEmail; }
  public void setGuardianEmail(String guardianEmail) { this.guardianEmail = guardianEmail; }

  public String getGuardianName() { return guardianName; }
  public void setGuardianName(String guardianName) { this.guardianName = guardianName; }

  public String getChildName() { return childName; }
  public void setChildName(String childName) { this.childName = childName; }

  public String getChildEmail() { return childEmail; }
  public void setChildEmail(String childEmail) { this.childEmail = childEmail; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getEntryTitle() { return entryTitle; }
  public void setEntryTitle(String entryTitle) { this.entryTitle = entryTitle; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getDivision() { return division; }
  public void setDivision(String division) { this.division = division; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getDeclineReason() { return declineReason; }
  public void setDeclineReason(String declineReason) { this.declineReason = declineReason; }

  public Instant getDecidedAt() { return decidedAt; }
  public void setDecidedAt(Instant decidedAt) { this.decidedAt = decidedAt; }

  public Instant getNotifiedAt() { return notifiedAt; }
  public void setNotifiedAt(Instant notifiedAt) { this.notifiedAt = notifiedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
