package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `host_application_draft` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "host_application_draft")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class HostApplicationDraftEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "owner_email", length = 255)
  private String ownerEmail;

  @Column(name = "owner_id", length = 255)
  private String ownerId;

  @Column(name = "answers", columnDefinition = "LONGTEXT")
  private String answers;

  @Column(name = "revision")
  private Double revision;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "pricing_snapshot", columnDefinition = "LONGTEXT")
  private String pricingSnapshot;

  @Column(name = "proposal_id", length = 255)
  private String proposalId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getOwnerEmail() { return ownerEmail; }
  public void setOwnerEmail(String ownerEmail) { this.ownerEmail = ownerEmail; }

  public String getOwnerId() { return ownerId; }
  public void setOwnerId(String ownerId) { this.ownerId = ownerId; }

  public String getAnswers() { return answers; }
  public void setAnswers(String answers) { this.answers = answers; }

  public Double getRevision() { return revision; }
  public void setRevision(Double revision) { this.revision = revision; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getPricingSnapshot() { return pricingSnapshot; }
  public void setPricingSnapshot(String pricingSnapshot) { this.pricingSnapshot = pricingSnapshot; }

  public String getProposalId() { return proposalId; }
  public void setProposalId(String proposalId) { this.proposalId = proposalId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
