package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `host_invoice` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "host_invoice")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class HostInvoiceEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "owner_email", length = 255)
  private String ownerEmail;

  @Column(name = "organisation_id", length = 255)
  private String organisationId;

  @Column(name = "draft_id", length = 255)
  private String draftId;

  @Column(name = "proposal_id", length = 255)
  private String proposalId;

  @Column(name = "purpose", length = 64)
  private String purpose;

  @Column(name = "label", length = 255)
  private String label;

  @Column(name = "amount")
  private Double amount;

  @Column(name = "currency", length = 255)
  private String currency;

  @Column(name = "line_items", columnDefinition = "LONGTEXT")
  private String lineItems;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "stripe_payment_intent_id", length = 255)
  private String stripePaymentIntentId;

  @Column(name = "paid_at")
  private Instant paidAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getOwnerEmail() { return ownerEmail; }
  public void setOwnerEmail(String ownerEmail) { this.ownerEmail = ownerEmail; }

  public String getOrganisationId() { return organisationId; }
  public void setOrganisationId(String organisationId) { this.organisationId = organisationId; }

  public String getDraftId() { return draftId; }
  public void setDraftId(String draftId) { this.draftId = draftId; }

  public String getProposalId() { return proposalId; }
  public void setProposalId(String proposalId) { this.proposalId = proposalId; }

  public String getPurpose() { return purpose; }
  public void setPurpose(String purpose) { this.purpose = purpose; }

  public String getLabel() { return label; }
  public void setLabel(String label) { this.label = label; }

  public Double getAmount() { return amount; }
  public void setAmount(Double amount) { this.amount = amount; }

  public String getCurrency() { return currency; }
  public void setCurrency(String currency) { this.currency = currency; }

  public String getLineItems() { return lineItems; }
  public void setLineItems(String lineItems) { this.lineItems = lineItems; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getStripePaymentIntentId() { return stripePaymentIntentId; }
  public void setStripePaymentIntentId(String stripePaymentIntentId) { this.stripePaymentIntentId = stripePaymentIntentId; }

  public Instant getPaidAt() { return paidAt; }
  public void setPaidAt(Instant paidAt) { this.paidAt = paidAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
