package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `host_organisation` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "host_organisation")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class HostOrganisationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "account_type_id", length = 255)
  private String accountTypeId;

  @Column(name = "abn", length = 255)
  private String abn;

  @Column(name = "contacts", length = 255)
  private String contacts;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "billing_status", length = 64)
  private String billingStatus;

  @Column(name = "internal_notes", columnDefinition = "LONGTEXT")
  private String internalNotes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getAccountTypeId() { return accountTypeId; }
  public void setAccountTypeId(String accountTypeId) { this.accountTypeId = accountTypeId; }

  public String getAbn() { return abn; }
  public void setAbn(String abn) { this.abn = abn; }

  public String getContacts() { return contacts; }
  public void setContacts(String contacts) { this.contacts = contacts; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getBillingStatus() { return billingStatus; }
  public void setBillingStatus(String billingStatus) { this.billingStatus = billingStatus; }

  public String getInternalNotes() { return internalNotes; }
  public void setInternalNotes(String internalNotes) { this.internalNotes = internalNotes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
