package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `intake_response` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "intake_response")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class IntakeResponseEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "host_organisation_id", length = 255)
  private String hostOrganisationId;

  @Column(name = "questionnaire_id", length = 255)
  private String questionnaireId;

  @Column(name = "questionnaire_version")
  private Double questionnaireVersion;

  @Column(name = "selected_option_ids", columnDefinition = "LONGTEXT")
  private String selectedOptionIds;

  @Column(name = "free_text_answers", columnDefinition = "LONGTEXT")
  private String freeTextAnswers;

  @Column(name = "submitted_at")
  private Instant submittedAt;

  @Column(name = "recommendation_id", length = 255)
  private String recommendationId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getHostOrganisationId() { return hostOrganisationId; }
  public void setHostOrganisationId(String hostOrganisationId) { this.hostOrganisationId = hostOrganisationId; }

  public String getQuestionnaireId() { return questionnaireId; }
  public void setQuestionnaireId(String questionnaireId) { this.questionnaireId = questionnaireId; }

  public Double getQuestionnaireVersion() { return questionnaireVersion; }
  public void setQuestionnaireVersion(Double questionnaireVersion) { this.questionnaireVersion = questionnaireVersion; }

  public String getSelectedOptionIds() { return selectedOptionIds; }
  public void setSelectedOptionIds(String selectedOptionIds) { this.selectedOptionIds = selectedOptionIds; }

  public String getFreeTextAnswers() { return freeTextAnswers; }
  public void setFreeTextAnswers(String freeTextAnswers) { this.freeTextAnswers = freeTextAnswers; }

  public Instant getSubmittedAt() { return submittedAt; }
  public void setSubmittedAt(Instant submittedAt) { this.submittedAt = submittedAt; }

  public String getRecommendationId() { return recommendationId; }
  public void setRecommendationId(String recommendationId) { this.recommendationId = recommendationId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
