package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `intake_question` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "intake_question")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class IntakeQuestionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "questionnaire_id", length = 255)
  private String questionnaireId;

  @Column(name = "prompt", length = 255)
  private String prompt;

  @Column(name = "type", length = 64)
  private String type;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "is_required")
  private Boolean isRequired;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getQuestionnaireId() { return questionnaireId; }
  public void setQuestionnaireId(String questionnaireId) { this.questionnaireId = questionnaireId; }

  public String getPrompt() { return prompt; }
  public void setPrompt(String prompt) { this.prompt = prompt; }

  public String getType() { return type; }
  public void setType(String type) { this.type = type; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public Boolean getIsRequired() { return isRequired; }
  public void setIsRequired(Boolean isRequired) { this.isRequired = isRequired; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
