package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `intake_answer_option` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "intake_answer_option")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class IntakeAnswerOptionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "question_id", length = 255)
  private String questionId;

  @Column(name = "label", length = 255)
  private String label;

  @Column(name = "weight")
  private Double weight;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "mechanic_ids", columnDefinition = "LONGTEXT")
  private String mechanicIds;

  @Column(name = "category_ids", columnDefinition = "LONGTEXT")
  private String categoryIds;

  @Column(name = "mode_ids", columnDefinition = "LONGTEXT")
  private String modeIds;

  @Column(name = "audience_ids", columnDefinition = "LONGTEXT")
  private String audienceIds;

  @Column(name = "scoring_ids", columnDefinition = "LONGTEXT")
  private String scoringIds;

  @Column(name = "evidence_ids", columnDefinition = "LONGTEXT")
  private String evidenceIds;

  @Column(name = "pathway_ids", columnDefinition = "LONGTEXT")
  private String pathwayIds;

  @Column(name = "service_tier_id", length = 255)
  private String serviceTierId;

  @Column(name = "scale_band_id", length = 255)
  private String scaleBandId;

  @Column(name = "program_scope", length = 64)
  private String programScope;

  @Column(name = "compliance_flags", columnDefinition = "LONGTEXT")
  private String complianceFlags;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getQuestionId() { return questionId; }
  public void setQuestionId(String questionId) { this.questionId = questionId; }

  public String getLabel() { return label; }
  public void setLabel(String label) { this.label = label; }

  public Double getWeight() { return weight; }
  public void setWeight(Double weight) { this.weight = weight; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public String getMechanicIds() { return mechanicIds; }
  public void setMechanicIds(String mechanicIds) { this.mechanicIds = mechanicIds; }

  public String getCategoryIds() { return categoryIds; }
  public void setCategoryIds(String categoryIds) { this.categoryIds = categoryIds; }

  public String getModeIds() { return modeIds; }
  public void setModeIds(String modeIds) { this.modeIds = modeIds; }

  public String getAudienceIds() { return audienceIds; }
  public void setAudienceIds(String audienceIds) { this.audienceIds = audienceIds; }

  public String getScoringIds() { return scoringIds; }
  public void setScoringIds(String scoringIds) { this.scoringIds = scoringIds; }

  public String getEvidenceIds() { return evidenceIds; }
  public void setEvidenceIds(String evidenceIds) { this.evidenceIds = evidenceIds; }

  public String getPathwayIds() { return pathwayIds; }
  public void setPathwayIds(String pathwayIds) { this.pathwayIds = pathwayIds; }

  public String getServiceTierId() { return serviceTierId; }
  public void setServiceTierId(String serviceTierId) { this.serviceTierId = serviceTierId; }

  public String getScaleBandId() { return scaleBandId; }
  public void setScaleBandId(String scaleBandId) { this.scaleBandId = scaleBandId; }

  public String getProgramScope() { return programScope; }
  public void setProgramScope(String programScope) { this.programScope = programScope; }

  public String getComplianceFlags() { return complianceFlags; }
  public void setComplianceFlags(String complianceFlags) { this.complianceFlags = complianceFlags; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
