package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `judging_panel` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "judging_panel")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class JudgingPanelEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "competition_title", length = 255)
  private String competitionTitle;

  @Column(name = "competition_category", length = 255)
  private String competitionCategory;

  @Column(name = "head_judge_profile_id", length = 1024)
  private String headJudgeProfileId;

  @Column(name = "head_judge_name", length = 255)
  private String headJudgeName;

  @Column(name = "judge_profile_ids", columnDefinition = "LONGTEXT")
  private String judgeProfileIds;

  @Column(name = "criteria", columnDefinition = "LONGTEXT")
  private String criteria;

  @Column(name = "scale_max")
  private Double scaleMax;

  @Column(name = "tie_breaker_index")
  private Double tieBreakerIndex;

  @Column(name = "calibration_entry_ids", columnDefinition = "LONGTEXT")
  private String calibrationEntryIds;

  @Column(name = "judge_weight")
  private Double judgeWeight;

  @Column(name = "public_weight")
  private Double publicWeight;

  @Column(name = "weighting_visible")
  private Boolean weightingVisible;

  @Column(name = "results_locked")
  private Boolean resultsLocked;

  @Column(name = "results_locked_at")
  private Instant resultsLockedAt;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getCompetitionTitle() { return competitionTitle; }
  public void setCompetitionTitle(String competitionTitle) { this.competitionTitle = competitionTitle; }

  public String getCompetitionCategory() { return competitionCategory; }
  public void setCompetitionCategory(String competitionCategory) { this.competitionCategory = competitionCategory; }

  public String getHeadJudgeProfileId() { return headJudgeProfileId; }
  public void setHeadJudgeProfileId(String headJudgeProfileId) { this.headJudgeProfileId = headJudgeProfileId; }

  public String getHeadJudgeName() { return headJudgeName; }
  public void setHeadJudgeName(String headJudgeName) { this.headJudgeName = headJudgeName; }

  public String getJudgeProfileIds() { return judgeProfileIds; }
  public void setJudgeProfileIds(String judgeProfileIds) { this.judgeProfileIds = judgeProfileIds; }

  public String getCriteria() { return criteria; }
  public void setCriteria(String criteria) { this.criteria = criteria; }

  public Double getScaleMax() { return scaleMax; }
  public void setScaleMax(Double scaleMax) { this.scaleMax = scaleMax; }

  public Double getTieBreakerIndex() { return tieBreakerIndex; }
  public void setTieBreakerIndex(Double tieBreakerIndex) { this.tieBreakerIndex = tieBreakerIndex; }

  public String getCalibrationEntryIds() { return calibrationEntryIds; }
  public void setCalibrationEntryIds(String calibrationEntryIds) { this.calibrationEntryIds = calibrationEntryIds; }

  public Double getJudgeWeight() { return judgeWeight; }
  public void setJudgeWeight(Double judgeWeight) { this.judgeWeight = judgeWeight; }

  public Double getPublicWeight() { return publicWeight; }
  public void setPublicWeight(Double publicWeight) { this.publicWeight = publicWeight; }

  public Boolean getWeightingVisible() { return weightingVisible; }
  public void setWeightingVisible(Boolean weightingVisible) { this.weightingVisible = weightingVisible; }

  public Boolean getResultsLocked() { return resultsLocked; }
  public void setResultsLocked(Boolean resultsLocked) { this.resultsLocked = resultsLocked; }

  public Instant getResultsLockedAt() { return resultsLockedAt; }
  public void setResultsLockedAt(Instant resultsLockedAt) { this.resultsLockedAt = resultsLockedAt; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
