package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Maps the `judge_profile` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "judge_profile")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class JudgeProfileEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "email", length = 255)
  private String email;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "applied_categories", columnDefinition = "LONGTEXT")
  private String appliedCategories;

  @Column(name = "approved_categories", columnDefinition = "LONGTEXT")
  private String approvedCategories;

  @Column(name = "experience", length = 255)
  private String experience;

  @Column(name = "availability", length = 255)
  private String availability;

  @Column(name = "credential_notes", columnDefinition = "LONGTEXT")
  private String credentialNotes;

  @Column(name = "wwcc_status", length = 64)
  private String wwccStatus;

  @Column(name = "wwcc_number", length = 255)
  private String wwccNumber;

  @Column(name = "wwcc_expiry")
  private LocalDate wwccExpiry;

  @Column(name = "agreement_signed")
  private Boolean agreementSigned;

  @Column(name = "agreement_signed_at")
  private Instant agreementSignedAt;

  @Column(name = "conflict_of_interest", columnDefinition = "LONGTEXT")
  private String conflictOfInterest;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "user_id", length = 255)
  private String userId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getEmail() { return email; }
  public void setEmail(String email) { this.email = email; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getAppliedCategories() { return appliedCategories; }
  public void setAppliedCategories(String appliedCategories) { this.appliedCategories = appliedCategories; }

  public String getApprovedCategories() { return approvedCategories; }
  public void setApprovedCategories(String approvedCategories) { this.approvedCategories = approvedCategories; }

  public String getExperience() { return experience; }
  public void setExperience(String experience) { this.experience = experience; }

  public String getAvailability() { return availability; }
  public void setAvailability(String availability) { this.availability = availability; }

  public String getCredentialNotes() { return credentialNotes; }
  public void setCredentialNotes(String credentialNotes) { this.credentialNotes = credentialNotes; }

  public String getWwccStatus() { return wwccStatus; }
  public void setWwccStatus(String wwccStatus) { this.wwccStatus = wwccStatus; }

  public String getWwccNumber() { return wwccNumber; }
  public void setWwccNumber(String wwccNumber) { this.wwccNumber = wwccNumber; }

  public LocalDate getWwccExpiry() { return wwccExpiry; }
  public void setWwccExpiry(LocalDate wwccExpiry) { this.wwccExpiry = wwccExpiry; }

  public Boolean getAgreementSigned() { return agreementSigned; }
  public void setAgreementSigned(Boolean agreementSigned) { this.agreementSigned = agreementSigned; }

  public Instant getAgreementSignedAt() { return agreementSignedAt; }
  public void setAgreementSignedAt(Instant agreementSignedAt) { this.agreementSignedAt = agreementSignedAt; }

  public String getConflictOfInterest() { return conflictOfInterest; }
  public void setConflictOfInterest(String conflictOfInterest) { this.conflictOfInterest = conflictOfInterest; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getUserId() { return userId; }
  public void setUserId(String userId) { this.userId = userId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
