package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `launch_competition` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "launch_competition")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class LaunchCompetitionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "category", length = 255)
  private String category;

  @Column(name = "subcategory", length = 255)
  private String subcategory;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "geography", length = 64)
  private String geography;

  @Column(name = "mechanic", length = 255)
  private String mechanic;

  @Column(name = "participation", length = 255)
  private String participation;

  @Column(name = "evidence", length = 255)
  private String evidence;

  @Column(name = "scoring_model", length = 255)
  private String scoringModel;

  @Column(name = "audience", length = 255)
  private String audience;

  @Column(name = "pathway", length = 255)
  private String pathway;

  @Column(name = "module_extensions", columnDefinition = "LONGTEXT")
  private String moduleExtensions;

  @Column(name = "hold_for_audit")
  private Boolean holdForAudit;

  @Column(name = "brief", columnDefinition = "LONGTEXT")
  private String brief;

  @Column(name = "eoi_count")
  private Double eoiCount;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getSubcategory() { return subcategory; }
  public void setSubcategory(String subcategory) { this.subcategory = subcategory; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getGeography() { return geography; }
  public void setGeography(String geography) { this.geography = geography; }

  public String getMechanic() { return mechanic; }
  public void setMechanic(String mechanic) { this.mechanic = mechanic; }

  public String getParticipation() { return participation; }
  public void setParticipation(String participation) { this.participation = participation; }

  public String getEvidence() { return evidence; }
  public void setEvidence(String evidence) { this.evidence = evidence; }

  public String getScoringModel() { return scoringModel; }
  public void setScoringModel(String scoringModel) { this.scoringModel = scoringModel; }

  public String getAudience() { return audience; }
  public void setAudience(String audience) { this.audience = audience; }

  public String getPathway() { return pathway; }
  public void setPathway(String pathway) { this.pathway = pathway; }

  public String getModuleExtensions() { return moduleExtensions; }
  public void setModuleExtensions(String moduleExtensions) { this.moduleExtensions = moduleExtensions; }

  public Boolean getHoldForAudit() { return holdForAudit; }
  public void setHoldForAudit(Boolean holdForAudit) { this.holdForAudit = holdForAudit; }

  public String getBrief() { return brief; }
  public void setBrief(String brief) { this.brief = brief; }

  public Double getEoiCount() { return eoiCount; }
  public void setEoiCount(Double eoiCount) { this.eoiCount = eoiCount; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
