package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `legal_position` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "legal_position")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class LegalPositionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "topic", length = 255)
  private String topic;

  @Column(name = "position", length = 64)
  private String position;

  @Column(name = "source_document", length = 255)
  private String sourceDocument;

  @Column(name = "effective_from")
  private Instant effectiveFrom;

  @Column(name = "review_by", length = 255)
  private String reviewBy;

  @Column(name = "is_active")
  private Boolean isActive;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getTopic() { return topic; }
  public void setTopic(String topic) { this.topic = topic; }

  public String getPosition() { return position; }
  public void setPosition(String position) { this.position = position; }

  public String getSourceDocument() { return sourceDocument; }
  public void setSourceDocument(String sourceDocument) { this.sourceDocument = sourceDocument; }

  public Instant getEffectiveFrom() { return effectiveFrom; }
  public void setEffectiveFrom(Instant effectiveFrom) { this.effectiveFrom = effectiveFrom; }

  public String getReviewBy() { return reviewBy; }
  public void setReviewBy(String reviewBy) { this.reviewBy = reviewBy; }

  public Boolean getIsActive() { return isActive; }
  public void setIsActive(Boolean isActive) { this.isActive = isActive; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
