package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `marketing_use_log` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "marketing_use_log")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class MarketingUseLogEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "participant_name", length = 255)
  private String participantName;

  @Column(name = "used_by", length = 64)
  private String usedBy;

  @Column(name = "channel", length = 255)
  private String channel;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "url_or_file", length = 1024)
  private String urlOrFile;

  @Column(name = "scopes_relied_on", columnDefinition = "LONGTEXT")
  private String scopesReliedOn;

  @Column(name = "checked_by", length = 255)
  private String checkedBy;

  @Column(name = "used_at")
  private Instant usedAt;

  @Column(name = "takedown_status", length = 64)
  private String takedownStatus;

  @Column(name = "takedown_at")
  private Instant takedownAt;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getParticipantName() { return participantName; }
  public void setParticipantName(String participantName) { this.participantName = participantName; }

  public String getUsedBy() { return usedBy; }
  public void setUsedBy(String usedBy) { this.usedBy = usedBy; }

  public String getChannel() { return channel; }
  public void setChannel(String channel) { this.channel = channel; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public String getUrlOrFile() { return urlOrFile; }
  public void setUrlOrFile(String urlOrFile) { this.urlOrFile = urlOrFile; }

  public String getScopesReliedOn() { return scopesReliedOn; }
  public void setScopesReliedOn(String scopesReliedOn) { this.scopesReliedOn = scopesReliedOn; }

  public String getCheckedBy() { return checkedBy; }
  public void setCheckedBy(String checkedBy) { this.checkedBy = checkedBy; }

  public Instant getUsedAt() { return usedAt; }
  public void setUsedAt(Instant usedAt) { this.usedAt = usedAt; }

  public String getTakedownStatus() { return takedownStatus; }
  public void setTakedownStatus(String takedownStatus) { this.takedownStatus = takedownStatus; }

  public Instant getTakedownAt() { return takedownAt; }
  public void setTakedownAt(Instant takedownAt) { this.takedownAt = takedownAt; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
