package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `media_release` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "media_release")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class MediaReleaseEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "subject_name", length = 255)
  private String subjectName;

  @Column(name = "subject_type", length = 64)
  private String subjectType;

  @Column(name = "guardian_consent_id", length = 255)
  private String guardianConsentId;

  @Column(name = "scopes_released", columnDefinition = "LONGTEXT")
  private String scopesReleased;

  @Column(name = "method", length = 64)
  private String method;

  @Column(name = "release_file", length = 1024)
  private String releaseFile;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "granted_at")
  private Instant grantedAt;

  @Column(name = "withdrawn_at")
  private Instant withdrawnAt;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getSubjectName() { return subjectName; }
  public void setSubjectName(String subjectName) { this.subjectName = subjectName; }

  public String getSubjectType() { return subjectType; }
  public void setSubjectType(String subjectType) { this.subjectType = subjectType; }

  public String getGuardianConsentId() { return guardianConsentId; }
  public void setGuardianConsentId(String guardianConsentId) { this.guardianConsentId = guardianConsentId; }

  public String getScopesReleased() { return scopesReleased; }
  public void setScopesReleased(String scopesReleased) { this.scopesReleased = scopesReleased; }

  public String getMethod() { return method; }
  public void setMethod(String method) { this.method = method; }

  public String getReleaseFile() { return releaseFile; }
  public void setReleaseFile(String releaseFile) { this.releaseFile = releaseFile; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getGrantedAt() { return grantedAt; }
  public void setGrantedAt(Instant grantedAt) { this.grantedAt = grantedAt; }

  public Instant getWithdrawnAt() { return withdrawnAt; }
  public void setWithdrawnAt(Instant withdrawnAt) { this.withdrawnAt = withdrawnAt; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
