package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `message` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "message")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class MessageEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "subject", length = 255)
  private String subject;

  @Column(name = "body", columnDefinition = "LONGTEXT")
  private String body;

  @Column(name = "sender", length = 64)
  private String sender;

  @Column(name = "participant_email", length = 255)
  private String participantEmail;

  @Column(name = "participant_name", length = 255)
  private String participantName;

  @Column(name = "`read`")
  private Boolean read;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getSubject() { return subject; }
  public void setSubject(String subject) { this.subject = subject; }

  public String getBody() { return body; }
  public void setBody(String body) { this.body = body; }

  public String getSender() { return sender; }
  public void setSender(String sender) { this.sender = sender; }

  public String getParticipantEmail() { return participantEmail; }
  public void setParticipantEmail(String participantEmail) { this.participantEmail = participantEmail; }

  public String getParticipantName() { return participantName; }
  public void setParticipantName(String participantName) { this.participantName = participantName; }

  public Boolean getRead() { return read; }
  public void setRead(Boolean read) { this.read = read; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
