package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `music_declaration` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "music_declaration")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class MusicDeclarationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "basis", length = 64)
  private String basis;

  @Column(name = "track_title", length = 255)
  private String trackTitle;

  @Column(name = "track_artist", length = 255)
  private String trackArtist;

  @Column(name = "licence_evidence", length = 255)
  private String licenceEvidence;

  @Column(name = "clearance_status", length = 64)
  private String clearanceStatus;

  @Column(name = "declared_at")
  private Instant declaredAt;

  @Column(name = "cleared_at")
  private Instant clearedAt;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getBasis() { return basis; }
  public void setBasis(String basis) { this.basis = basis; }

  public String getTrackTitle() { return trackTitle; }
  public void setTrackTitle(String trackTitle) { this.trackTitle = trackTitle; }

  public String getTrackArtist() { return trackArtist; }
  public void setTrackArtist(String trackArtist) { this.trackArtist = trackArtist; }

  public String getLicenceEvidence() { return licenceEvidence; }
  public void setLicenceEvidence(String licenceEvidence) { this.licenceEvidence = licenceEvidence; }

  public String getClearanceStatus() { return clearanceStatus; }
  public void setClearanceStatus(String clearanceStatus) { this.clearanceStatus = clearanceStatus; }

  public Instant getDeclaredAt() { return declaredAt; }
  public void setDeclaredAt(Instant declaredAt) { this.declaredAt = declaredAt; }

  public Instant getClearedAt() { return clearedAt; }
  public void setClearedAt(Instant clearedAt) { this.clearedAt = clearedAt; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
