package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `obligation_evidence` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "obligation_evidence")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ObligationEvidenceEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "finding_id", length = 255)
  private String findingId;

  @Column(name = "evidence_type", length = 64)
  private String evidenceType;

  @Column(name = "file_record", length = 1024)
  private String fileRecord;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "recorded_by", length = 255)
  private String recordedBy;

  @Column(name = "recorded_at")
  private Instant recordedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getFindingId() { return findingId; }
  public void setFindingId(String findingId) { this.findingId = findingId; }

  public String getEvidenceType() { return evidenceType; }
  public void setEvidenceType(String evidenceType) { this.evidenceType = evidenceType; }

  public String getFileRecord() { return fileRecord; }
  public void setFileRecord(String fileRecord) { this.fileRecord = fileRecord; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public String getRecordedBy() { return recordedBy; }
  public void setRecordedBy(String recordedBy) { this.recordedBy = recordedBy; }

  public Instant getRecordedAt() { return recordedAt; }
  public void setRecordedAt(Instant recordedAt) { this.recordedAt = recordedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
