package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `organisation` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "organisation")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class OrganisationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "legal_name", length = 255)
  private String legalName;

  @Column(name = "kind", length = 64)
  private String kind;

  @Column(name = "signup_code", length = 255)
  private String signupCode;

  @Column(name = "abn", length = 255)
  private String abn;

  @Column(name = "account_type_id", length = 255)
  private String accountTypeId;

  @Column(name = "billing_status", length = 64)
  private String billingStatus;

  @Column(name = "verification_status", length = 64)
  private String verificationStatus;

  @Column(name = "contact_email", length = 255)
  private String contactEmail;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "internal_notes", columnDefinition = "LONGTEXT")
  private String internalNotes;

  @Column(name = "member_count")
  private Double memberCount;

  @Column(name = "entry_count")
  private Double entryCount;

  @Column(name = "vote_count")
  private Double voteCount;

  @Column(name = "leaderboard_enabled")
  private Boolean leaderboardEnabled;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getLegalName() { return legalName; }
  public void setLegalName(String legalName) { this.legalName = legalName; }

  public String getKind() { return kind; }
  public void setKind(String kind) { this.kind = kind; }

  public String getSignupCode() { return signupCode; }
  public void setSignupCode(String signupCode) { this.signupCode = signupCode; }

  public String getAbn() { return abn; }
  public void setAbn(String abn) { this.abn = abn; }

  public String getAccountTypeId() { return accountTypeId; }
  public void setAccountTypeId(String accountTypeId) { this.accountTypeId = accountTypeId; }

  public String getBillingStatus() { return billingStatus; }
  public void setBillingStatus(String billingStatus) { this.billingStatus = billingStatus; }

  public String getVerificationStatus() { return verificationStatus; }
  public void setVerificationStatus(String verificationStatus) { this.verificationStatus = verificationStatus; }

  public String getContactEmail() { return contactEmail; }
  public void setContactEmail(String contactEmail) { this.contactEmail = contactEmail; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public String getInternalNotes() { return internalNotes; }
  public void setInternalNotes(String internalNotes) { this.internalNotes = internalNotes; }

  public Double getMemberCount() { return memberCount; }
  public void setMemberCount(Double memberCount) { this.memberCount = memberCount; }

  public Double getEntryCount() { return entryCount; }
  public void setEntryCount(Double entryCount) { this.entryCount = entryCount; }

  public Double getVoteCount() { return voteCount; }
  public void setVoteCount(Double voteCount) { this.voteCount = voteCount; }

  public Boolean getLeaderboardEnabled() { return leaderboardEnabled; }
  public void setLeaderboardEnabled(Boolean leaderboardEnabled) { this.leaderboardEnabled = leaderboardEnabled; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
