package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `participant_rights_record` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "participant_rights_record")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ParticipantRightsRecordEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "participant_name", length = 255)
  private String participantName;

  @Column(name = "participant_email", length = 255)
  private String participantEmail;

  @Column(name = "is_minor")
  private Boolean isMinor;

  @Column(name = "guardian_consent_id", length = 255)
  private String guardianConsentId;

  @Column(name = "scope_grants", columnDefinition = "LONGTEXT")
  private String scopeGrants;

  @Column(name = "marketing_contact_grants", columnDefinition = "LONGTEXT")
  private String marketingContactGrants;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "accepted_at")
  private Instant acceptedAt;

  @Column(name = "revoked_at")
  private Instant revokedAt;

  @Column(name = "config_snapshot", columnDefinition = "LONGTEXT")
  private String configSnapshot;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getParticipantName() { return participantName; }
  public void setParticipantName(String participantName) { this.participantName = participantName; }

  public String getParticipantEmail() { return participantEmail; }
  public void setParticipantEmail(String participantEmail) { this.participantEmail = participantEmail; }

  public Boolean getIsMinor() { return isMinor; }
  public void setIsMinor(Boolean isMinor) { this.isMinor = isMinor; }

  public String getGuardianConsentId() { return guardianConsentId; }
  public void setGuardianConsentId(String guardianConsentId) { this.guardianConsentId = guardianConsentId; }

  public String getScopeGrants() { return scopeGrants; }
  public void setScopeGrants(String scopeGrants) { this.scopeGrants = scopeGrants; }

  public String getMarketingContactGrants() { return marketingContactGrants; }
  public void setMarketingContactGrants(String marketingContactGrants) { this.marketingContactGrants = marketingContactGrants; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getAcceptedAt() { return acceptedAt; }
  public void setAcceptedAt(Instant acceptedAt) { this.acceptedAt = acceptedAt; }

  public Instant getRevokedAt() { return revokedAt; }
  public void setRevokedAt(Instant revokedAt) { this.revokedAt = revokedAt; }

  public String getConfigSnapshot() { return configSnapshot; }
  public void setConfigSnapshot(String configSnapshot) { this.configSnapshot = configSnapshot; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
