package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `participant_post` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "participant_post")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ParticipantPostEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "owner_email", length = 255)
  private String ownerEmail;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "topic", length = 255)
  private String topic;

  @Column(name = "tone", length = 255)
  private String tone;

  @Column(name = "content", columnDefinition = "LONGTEXT")
  private String content;

  @Column(name = "hashtags", columnDefinition = "LONGTEXT")
  private String hashtags;

  @Column(name = "image_url", length = 1024)
  private String imageUrl;

  @Column(name = "platforms", columnDefinition = "LONGTEXT")
  private String platforms;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "shared_at")
  private Instant sharedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getOwnerEmail() { return ownerEmail; }
  public void setOwnerEmail(String ownerEmail) { this.ownerEmail = ownerEmail; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getTopic() { return topic; }
  public void setTopic(String topic) { this.topic = topic; }

  public String getTone() { return tone; }
  public void setTone(String tone) { this.tone = tone; }

  public String getContent() { return content; }
  public void setContent(String content) { this.content = content; }

  public String getHashtags() { return hashtags; }
  public void setHashtags(String hashtags) { this.hashtags = hashtags; }

  public String getImageUrl() { return imageUrl; }
  public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }

  public String getPlatforms() { return platforms; }
  public void setPlatforms(String platforms) { this.platforms = platforms; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getSharedAt() { return sharedAt; }
  public void setSharedAt(Instant sharedAt) { this.sharedAt = sharedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
