package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Maps the `partner_inquiry` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "partner_inquiry")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PartnerInquiryEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "owner_email", length = 255)
  private String ownerEmail;

  @Column(name = "parent_request_id", length = 255)
  private String parentRequestId;

  @Column(name = "company_name", length = 255)
  private String companyName;

  @Column(name = "company_website", length = 255)
  private String companyWebsite;

  @Column(name = "industry", length = 255)
  private String industry;

  @Column(name = "contact_name", length = 255)
  private String contactName;

  @Column(name = "contact_email", length = 255)
  private String contactEmail;

  @Column(name = "contact_phone", length = 255)
  private String contactPhone;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "challenge_type", length = 255)
  private String challengeType;

  @Column(name = "challenge_goal", length = 255)
  private String challengeGoal;

  @Column(name = "challenge_description", columnDefinition = "LONGTEXT")
  private String challengeDescription;

  @Column(name = "audience_description", columnDefinition = "LONGTEXT")
  private String audienceDescription;

  @Column(name = "audience_size", length = 255)
  private String audienceSize;

  @Column(name = "geographic_scope", length = 255)
  private String geographicScope;

  @Column(name = "launch_timing", length = 255)
  private String launchTiming;

  @Column(name = "start_date")
  private LocalDate startDate;

  @Column(name = "end_date")
  private LocalDate endDate;

  @Column(name = "estimated_budget", length = 255)
  private String estimatedBudget;

  @Column(name = "prize_format", length = 255)
  private String prizeFormat;

  @Column(name = "additional_notes", columnDefinition = "LONGTEXT")
  private String additionalNotes;

  @Column(name = "how_heard", length = 255)
  private String howHeard;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "internal_notes", columnDefinition = "LONGTEXT")
  private String internalNotes;

  @Column(name = "ai_plan", columnDefinition = "LONGTEXT")
  private String aiPlan;

  @Column(name = "organisation_kind", length = 64)
  private String organisationKind;

  @Column(name = "pipeline_status", length = 64)
  private String pipelineStatus;

  @Column(name = "sponsor_profile_id", length = 1024)
  private String sponsorProfileId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getOwnerEmail() { return ownerEmail; }
  public void setOwnerEmail(String ownerEmail) { this.ownerEmail = ownerEmail; }

  public String getParentRequestId() { return parentRequestId; }
  public void setParentRequestId(String parentRequestId) { this.parentRequestId = parentRequestId; }

  public String getCompanyName() { return companyName; }
  public void setCompanyName(String companyName) { this.companyName = companyName; }

  public String getCompanyWebsite() { return companyWebsite; }
  public void setCompanyWebsite(String companyWebsite) { this.companyWebsite = companyWebsite; }

  public String getIndustry() { return industry; }
  public void setIndustry(String industry) { this.industry = industry; }

  public String getContactName() { return contactName; }
  public void setContactName(String contactName) { this.contactName = contactName; }

  public String getContactEmail() { return contactEmail; }
  public void setContactEmail(String contactEmail) { this.contactEmail = contactEmail; }

  public String getContactPhone() { return contactPhone; }
  public void setContactPhone(String contactPhone) { this.contactPhone = contactPhone; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getChallengeType() { return challengeType; }
  public void setChallengeType(String challengeType) { this.challengeType = challengeType; }

  public String getChallengeGoal() { return challengeGoal; }
  public void setChallengeGoal(String challengeGoal) { this.challengeGoal = challengeGoal; }

  public String getChallengeDescription() { return challengeDescription; }
  public void setChallengeDescription(String challengeDescription) { this.challengeDescription = challengeDescription; }

  public String getAudienceDescription() { return audienceDescription; }
  public void setAudienceDescription(String audienceDescription) { this.audienceDescription = audienceDescription; }

  public String getAudienceSize() { return audienceSize; }
  public void setAudienceSize(String audienceSize) { this.audienceSize = audienceSize; }

  public String getGeographicScope() { return geographicScope; }
  public void setGeographicScope(String geographicScope) { this.geographicScope = geographicScope; }

  public String getLaunchTiming() { return launchTiming; }
  public void setLaunchTiming(String launchTiming) { this.launchTiming = launchTiming; }

  public LocalDate getStartDate() { return startDate; }
  public void setStartDate(LocalDate startDate) { this.startDate = startDate; }

  public LocalDate getEndDate() { return endDate; }
  public void setEndDate(LocalDate endDate) { this.endDate = endDate; }

  public String getEstimatedBudget() { return estimatedBudget; }
  public void setEstimatedBudget(String estimatedBudget) { this.estimatedBudget = estimatedBudget; }

  public String getPrizeFormat() { return prizeFormat; }
  public void setPrizeFormat(String prizeFormat) { this.prizeFormat = prizeFormat; }

  public String getAdditionalNotes() { return additionalNotes; }
  public void setAdditionalNotes(String additionalNotes) { this.additionalNotes = additionalNotes; }

  public String getHowHeard() { return howHeard; }
  public void setHowHeard(String howHeard) { this.howHeard = howHeard; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getInternalNotes() { return internalNotes; }
  public void setInternalNotes(String internalNotes) { this.internalNotes = internalNotes; }

  public String getAiPlan() { return aiPlan; }
  public void setAiPlan(String aiPlan) { this.aiPlan = aiPlan; }

  public String getOrganisationKind() { return organisationKind; }
  public void setOrganisationKind(String organisationKind) { this.organisationKind = organisationKind; }

  public String getPipelineStatus() { return pipelineStatus; }
  public void setPipelineStatus(String pipelineStatus) { this.pipelineStatus = pipelineStatus; }

  public String getSponsorProfileId() { return sponsorProfileId; }
  public void setSponsorProfileId(String sponsorProfileId) { this.sponsorProfileId = sponsorProfileId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
