package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `pathway` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "pathway")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PathwayEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "type", length = 64)
  private String type;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "season_label", length = 255)
  private String seasonLabel;

  @Column(name = "anchor_challenge_id", length = 255)
  private String anchorChallengeId;

  @Column(name = "access_code", length = 255)
  private String accessCode;

  @Column(name = "approved_organisations", columnDefinition = "LONGTEXT")
  private String approvedOrganisations;

  @Column(name = "invited_emails", columnDefinition = "LONGTEXT")
  private String invitedEmails;

  @Column(name = "points_scale", columnDefinition = "LONGTEXT")
  private String pointsScale;

  @Column(name = "promotion_count")
  private Double promotionCount;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getType() { return type; }
  public void setType(String type) { this.type = type; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public String getSeasonLabel() { return seasonLabel; }
  public void setSeasonLabel(String seasonLabel) { this.seasonLabel = seasonLabel; }

  public String getAnchorChallengeId() { return anchorChallengeId; }
  public void setAnchorChallengeId(String anchorChallengeId) { this.anchorChallengeId = anchorChallengeId; }

  public String getAccessCode() { return accessCode; }
  public void setAccessCode(String accessCode) { this.accessCode = accessCode; }

  public String getApprovedOrganisations() { return approvedOrganisations; }
  public void setApprovedOrganisations(String approvedOrganisations) { this.approvedOrganisations = approvedOrganisations; }

  public String getInvitedEmails() { return invitedEmails; }
  public void setInvitedEmails(String invitedEmails) { this.invitedEmails = invitedEmails; }

  public String getPointsScale() { return pointsScale; }
  public void setPointsScale(String pointsScale) { this.pointsScale = pointsScale; }

  public Double getPromotionCount() { return promotionCount; }
  public void setPromotionCount(Double promotionCount) { this.promotionCount = promotionCount; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
