package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `pathway_member` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "pathway_member")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PathwayMemberEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "pathway_id", length = 255)
  private String pathwayId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "challenge_title", length = 255)
  private String challengeTitle;

  @Column(name = "member_kind", length = 64)
  private String memberKind;

  @Column(name = "region", length = 255)
  private String region;

  @Column(name = "tier")
  private Double tier;

  @Column(name = "promotion_to_challenge_id", length = 255)
  private String promotionToChallengeId;

  @Column(name = "promotion_count_override")
  private Double promotionCountOverride;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPathwayId() { return pathwayId; }
  public void setPathwayId(String pathwayId) { this.pathwayId = pathwayId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getChallengeTitle() { return challengeTitle; }
  public void setChallengeTitle(String challengeTitle) { this.challengeTitle = challengeTitle; }

  public String getMemberKind() { return memberKind; }
  public void setMemberKind(String memberKind) { this.memberKind = memberKind; }

  public String getRegion() { return region; }
  public void setRegion(String region) { this.region = region; }

  public Double getTier() { return tier; }
  public void setTier(Double tier) { this.tier = tier; }

  public String getPromotionToChallengeId() { return promotionToChallengeId; }
  public void setPromotionToChallengeId(String promotionToChallengeId) { this.promotionToChallengeId = promotionToChallengeId; }

  public Double getPromotionCountOverride() { return promotionCountOverride; }
  public void setPromotionCountOverride(Double promotionCountOverride) { this.promotionCountOverride = promotionCountOverride; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
