package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Maps the `permit_or_authority` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "permit_or_authority")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PermitOrAuthorityEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "jurisdiction_code", length = 64)
  private String jurisdictionCode;

  @Column(name = "instrument_type", length = 64)
  private String instrumentType;

  @Column(name = "holder", length = 64)
  private String holder;

  @Column(name = "holder_entity_name", length = 255)
  private String holderEntityName;

  @Column(name = "reference_number", length = 255)
  private String referenceNumber;

  @Column(name = "issued_date")
  private LocalDate issuedDate;

  @Column(name = "effective_date")
  private LocalDate effectiveDate;

  @Column(name = "expiry_date")
  private LocalDate expiryDate;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "covered_challenges", columnDefinition = "LONGTEXT")
  private String coveredChallenges;

  @Column(name = "fee")
  private Double fee;

  @Column(name = "documents", columnDefinition = "LONGTEXT")
  private String documents;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getJurisdictionCode() { return jurisdictionCode; }
  public void setJurisdictionCode(String jurisdictionCode) { this.jurisdictionCode = jurisdictionCode; }

  public String getInstrumentType() { return instrumentType; }
  public void setInstrumentType(String instrumentType) { this.instrumentType = instrumentType; }

  public String getHolder() { return holder; }
  public void setHolder(String holder) { this.holder = holder; }

  public String getHolderEntityName() { return holderEntityName; }
  public void setHolderEntityName(String holderEntityName) { this.holderEntityName = holderEntityName; }

  public String getReferenceNumber() { return referenceNumber; }
  public void setReferenceNumber(String referenceNumber) { this.referenceNumber = referenceNumber; }

  public LocalDate getIssuedDate() { return issuedDate; }
  public void setIssuedDate(LocalDate issuedDate) { this.issuedDate = issuedDate; }

  public LocalDate getEffectiveDate() { return effectiveDate; }
  public void setEffectiveDate(LocalDate effectiveDate) { this.effectiveDate = effectiveDate; }

  public LocalDate getExpiryDate() { return expiryDate; }
  public void setExpiryDate(LocalDate expiryDate) { this.expiryDate = expiryDate; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getCoveredChallenges() { return coveredChallenges; }
  public void setCoveredChallenges(String coveredChallenges) { this.coveredChallenges = coveredChallenges; }

  public Double getFee() { return fee; }
  public void setFee(Double fee) { this.fee = fee; }

  public String getDocuments() { return documents; }
  public void setDocuments(String documents) { this.documents = documents; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
