package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * Maps the `permit_action` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "permit_action")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PermitActionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "instrument_id", length = 255)
  private String instrumentId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "action_type", length = 64)
  private String actionType;

  @Column(name = "due_date")
  private LocalDate dueDate;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "assigned_to", length = 255)
  private String assignedTo;

  @Column(name = "evidence", length = 255)
  private String evidence;

  @Column(name = "completed_at")
  private Instant completedAt;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getInstrumentId() { return instrumentId; }
  public void setInstrumentId(String instrumentId) { this.instrumentId = instrumentId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getActionType() { return actionType; }
  public void setActionType(String actionType) { this.actionType = actionType; }

  public LocalDate getDueDate() { return dueDate; }
  public void setDueDate(LocalDate dueDate) { this.dueDate = dueDate; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getAssignedTo() { return assignedTo; }
  public void setAssignedTo(String assignedTo) { this.assignedTo = assignedTo; }

  public String getEvidence() { return evidence; }
  public void setEvidence(String evidence) { this.evidence = evidence; }

  public Instant getCompletedAt() { return completedAt; }
  public void setCompletedAt(Instant completedAt) { this.completedAt = completedAt; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
