package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `prize_ledger` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "prize_ledger")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PrizeLedgerEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "competition_title", length = 255)
  private String competitionTitle;

  @Column(name = "funding_source", length = 64)
  private String fundingSource;

  @Column(name = "sponsor_name", length = 255)
  private String sponsorName;

  @Column(name = "sponsor_amount")
  private Double sponsorAmount;

  @Column(name = "sponsor_received")
  private Boolean sponsorReceived;

  @Column(name = "sponsor_received_at")
  private Instant sponsorReceivedAt;

  @Column(name = "sponsor_received_by", length = 255)
  private String sponsorReceivedBy;

  @Column(name = "total_pool")
  private Double totalPool;

  @Column(name = "currency", length = 255)
  private String currency;

  @Column(name = "placings", columnDefinition = "LONGTEXT")
  private String placings;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "confirmed_by", length = 255)
  private String confirmedBy;

  @Column(name = "confirmed_at")
  private Instant confirmedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getCompetitionTitle() { return competitionTitle; }
  public void setCompetitionTitle(String competitionTitle) { this.competitionTitle = competitionTitle; }

  public String getFundingSource() { return fundingSource; }
  public void setFundingSource(String fundingSource) { this.fundingSource = fundingSource; }

  public String getSponsorName() { return sponsorName; }
  public void setSponsorName(String sponsorName) { this.sponsorName = sponsorName; }

  public Double getSponsorAmount() { return sponsorAmount; }
  public void setSponsorAmount(Double sponsorAmount) { this.sponsorAmount = sponsorAmount; }

  public Boolean getSponsorReceived() { return sponsorReceived; }
  public void setSponsorReceived(Boolean sponsorReceived) { this.sponsorReceived = sponsorReceived; }

  public Instant getSponsorReceivedAt() { return sponsorReceivedAt; }
  public void setSponsorReceivedAt(Instant sponsorReceivedAt) { this.sponsorReceivedAt = sponsorReceivedAt; }

  public String getSponsorReceivedBy() { return sponsorReceivedBy; }
  public void setSponsorReceivedBy(String sponsorReceivedBy) { this.sponsorReceivedBy = sponsorReceivedBy; }

  public Double getTotalPool() { return totalPool; }
  public void setTotalPool(Double totalPool) { this.totalPool = totalPool; }

  public String getCurrency() { return currency; }
  public void setCurrency(String currency) { this.currency = currency; }

  public String getPlacings() { return placings; }
  public void setPlacings(String placings) { this.placings = placings; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getConfirmedBy() { return confirmedBy; }
  public void setConfirmedBy(String confirmedBy) { this.confirmedBy = confirmedBy; }

  public Instant getConfirmedAt() { return confirmedAt; }
  public void setConfirmedAt(Instant confirmedAt) { this.confirmedAt = confirmedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
