package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `prize_payout` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "prize_payout")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PrizePayoutEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "ledger_id", length = 255)
  private String ledgerId;

  @Column(name = "competition_id", length = 255)
  private String competitionId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "placing")
  private Double placing;

  @Column(name = "label", length = 255)
  private String label;

  @Column(name = "amount")
  private Double amount;

  @Column(name = "winner_name", length = 255)
  private String winnerName;

  @Column(name = "is_minor")
  private Boolean isMinor;

  @Column(name = "payee_type", length = 64)
  private String payeeType;

  @Column(name = "payee_name", length = 255)
  private String payeeName;

  @Column(name = "guardian_name", length = 255)
  private String guardianName;

  @Column(name = "identity_verified")
  private Boolean identityVerified;

  @Column(name = "payment_details_verified")
  private Boolean paymentDetailsVerified;

  @Column(name = "payment_method", length = 255)
  private String paymentMethod;

  @Column(name = "payment_ref", length = 255)
  private String paymentRef;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "auditor_signoff_by", length = 255)
  private String auditorSignoffBy;

  @Column(name = "auditor_signoff_name", length = 255)
  private String auditorSignoffName;

  @Column(name = "auditor_signoff_at")
  private Instant auditorSignoffAt;

  @Column(name = "admin_approval_by", length = 255)
  private String adminApprovalBy;

  @Column(name = "admin_approval_name", length = 255)
  private String adminApprovalName;

  @Column(name = "admin_approval_at")
  private Instant adminApprovalAt;

  @Column(name = "paid_at")
  private Instant paidAt;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getLedgerId() { return ledgerId; }
  public void setLedgerId(String ledgerId) { this.ledgerId = ledgerId; }

  public String getCompetitionId() { return competitionId; }
  public void setCompetitionId(String competitionId) { this.competitionId = competitionId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public Double getPlacing() { return placing; }
  public void setPlacing(Double placing) { this.placing = placing; }

  public String getLabel() { return label; }
  public void setLabel(String label) { this.label = label; }

  public Double getAmount() { return amount; }
  public void setAmount(Double amount) { this.amount = amount; }

  public String getWinnerName() { return winnerName; }
  public void setWinnerName(String winnerName) { this.winnerName = winnerName; }

  public Boolean getIsMinor() { return isMinor; }
  public void setIsMinor(Boolean isMinor) { this.isMinor = isMinor; }

  public String getPayeeType() { return payeeType; }
  public void setPayeeType(String payeeType) { this.payeeType = payeeType; }

  public String getPayeeName() { return payeeName; }
  public void setPayeeName(String payeeName) { this.payeeName = payeeName; }

  public String getGuardianName() { return guardianName; }
  public void setGuardianName(String guardianName) { this.guardianName = guardianName; }

  public Boolean getIdentityVerified() { return identityVerified; }
  public void setIdentityVerified(Boolean identityVerified) { this.identityVerified = identityVerified; }

  public Boolean getPaymentDetailsVerified() { return paymentDetailsVerified; }
  public void setPaymentDetailsVerified(Boolean paymentDetailsVerified) { this.paymentDetailsVerified = paymentDetailsVerified; }

  public String getPaymentMethod() { return paymentMethod; }
  public void setPaymentMethod(String paymentMethod) { this.paymentMethod = paymentMethod; }

  public String getPaymentRef() { return paymentRef; }
  public void setPaymentRef(String paymentRef) { this.paymentRef = paymentRef; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getAuditorSignoffBy() { return auditorSignoffBy; }
  public void setAuditorSignoffBy(String auditorSignoffBy) { this.auditorSignoffBy = auditorSignoffBy; }

  public String getAuditorSignoffName() { return auditorSignoffName; }
  public void setAuditorSignoffName(String auditorSignoffName) { this.auditorSignoffName = auditorSignoffName; }

  public Instant getAuditorSignoffAt() { return auditorSignoffAt; }
  public void setAuditorSignoffAt(Instant auditorSignoffAt) { this.auditorSignoffAt = auditorSignoffAt; }

  public String getAdminApprovalBy() { return adminApprovalBy; }
  public void setAdminApprovalBy(String adminApprovalBy) { this.adminApprovalBy = adminApprovalBy; }

  public String getAdminApprovalName() { return adminApprovalName; }
  public void setAdminApprovalName(String adminApprovalName) { this.adminApprovalName = adminApprovalName; }

  public Instant getAdminApprovalAt() { return adminApprovalAt; }
  public void setAdminApprovalAt(Instant adminApprovalAt) { this.adminApprovalAt = adminApprovalAt; }

  public Instant getPaidAt() { return paidAt; }
  public void setPaidAt(Instant paidAt) { this.paidAt = paidAt; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
