package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `promoter_appointment` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "promoter_appointment")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PromoterAppointmentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "promoter_type", length = 64)
  private String promoterType;

  @Column(name = "promoter_entity_name", length = 255)
  private String promoterEntityName;

  @Column(name = "abn", length = 255)
  private String abn;

  @Column(name = "contact", length = 255)
  private String contact;

  @Column(name = "appointed_by", length = 255)
  private String appointedBy;

  @Column(name = "appointed_at")
  private Instant appointedAt;

  @Column(name = "basis_document", length = 255)
  private String basisDocument;

  @Column(name = "notes", columnDefinition = "LONGTEXT")
  private String notes;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getPromoterType() { return promoterType; }
  public void setPromoterType(String promoterType) { this.promoterType = promoterType; }

  public String getPromoterEntityName() { return promoterEntityName; }
  public void setPromoterEntityName(String promoterEntityName) { this.promoterEntityName = promoterEntityName; }

  public String getAbn() { return abn; }
  public void setAbn(String abn) { this.abn = abn; }

  public String getContact() { return contact; }
  public void setContact(String contact) { this.contact = contact; }

  public String getAppointedBy() { return appointedBy; }
  public void setAppointedBy(String appointedBy) { this.appointedBy = appointedBy; }

  public Instant getAppointedAt() { return appointedAt; }
  public void setAppointedAt(Instant appointedAt) { this.appointedAt = appointedAt; }

  public String getBasisDocument() { return basisDocument; }
  public void setBasisDocument(String basisDocument) { this.basisDocument = basisDocument; }

  public String getNotes() { return notes; }
  public void setNotes(String notes) { this.notes = notes; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
