package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `promotion` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "promotion")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class PromotionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "pathway_id", length = 255)
  private String pathwayId;

  @Column(name = "from_challenge_id", length = 255)
  private String fromChallengeId;

  @Column(name = "to_challenge_id", length = 255)
  private String toChallengeId;

  @Column(name = "source_entry_id", length = 255)
  private String sourceEntryId;

  @Column(name = "promoted_entry_id", length = 255)
  private String promotedEntryId;

  @Column(name = "creator_name", length = 255)
  private String creatorName;

  @Column(name = "region", length = 255)
  private String region;

  @Column(name = "placing")
  private Double placing;

  @Column(name = "promoted_at")
  private Instant promotedAt;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPathwayId() { return pathwayId; }
  public void setPathwayId(String pathwayId) { this.pathwayId = pathwayId; }

  public String getFromChallengeId() { return fromChallengeId; }
  public void setFromChallengeId(String fromChallengeId) { this.fromChallengeId = fromChallengeId; }

  public String getToChallengeId() { return toChallengeId; }
  public void setToChallengeId(String toChallengeId) { this.toChallengeId = toChallengeId; }

  public String getSourceEntryId() { return sourceEntryId; }
  public void setSourceEntryId(String sourceEntryId) { this.sourceEntryId = sourceEntryId; }

  public String getPromotedEntryId() { return promotedEntryId; }
  public void setPromotedEntryId(String promotedEntryId) { this.promotedEntryId = promotedEntryId; }

  public String getCreatorName() { return creatorName; }
  public void setCreatorName(String creatorName) { this.creatorName = creatorName; }

  public String getRegion() { return region; }
  public void setRegion(String region) { this.region = region; }

  public Double getPlacing() { return placing; }
  public void setPlacing(Double placing) { this.placing = placing; }

  public Instant getPromotedAt() { return promotedAt; }
  public void setPromotedAt(Instant promotedAt) { this.promotedAt = promotedAt; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
