package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `rate_card` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "rate_card")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class RateCardEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "version")
  private Double version;

  @Column(name = "is_active")
  private Boolean isActive;

  @Column(name = "superseded_by_id", length = 255)
  private String supersededById;

  @Column(name = "change_note", columnDefinition = "LONGTEXT")
  private String changeNote;

  @Column(name = "tier_base_fees", columnDefinition = "LONGTEXT")
  private String tierBaseFees;

  @Column(name = "participants_included", columnDefinition = "LONGTEXT")
  private String participantsIncluded;

  @Column(name = "per_extra_100", columnDefinition = "LONGTEXT")
  private String perExtra100;

  @Column(name = "weeks_included", columnDefinition = "LONGTEXT")
  private String weeksIncluded;

  @Column(name = "per_extra_week", columnDefinition = "LONGTEXT")
  private String perExtraWeek;

  @Column(name = "judging_fees", columnDefinition = "LONGTEXT")
  private String judgingFees;

  @Column(name = "permit_assistance_fee")
  private Double permitAssistanceFee;

  @Column(name = "prize_admin_pct")
  private Double prizeAdminPct;

  @Column(name = "addon_fees", columnDefinition = "LONGTEXT")
  private String addonFees;

  @Column(name = "program_discounts", columnDefinition = "LONGTEXT")
  private String programDiscounts;

  @Column(name = "gst_pct")
  private Double gstPct;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public Double getVersion() { return version; }
  public void setVersion(Double version) { this.version = version; }

  public Boolean getIsActive() { return isActive; }
  public void setIsActive(Boolean isActive) { this.isActive = isActive; }

  public String getSupersededById() { return supersededById; }
  public void setSupersededById(String supersededById) { this.supersededById = supersededById; }

  public String getChangeNote() { return changeNote; }
  public void setChangeNote(String changeNote) { this.changeNote = changeNote; }

  public String getTierBaseFees() { return tierBaseFees; }
  public void setTierBaseFees(String tierBaseFees) { this.tierBaseFees = tierBaseFees; }

  public String getParticipantsIncluded() { return participantsIncluded; }
  public void setParticipantsIncluded(String participantsIncluded) { this.participantsIncluded = participantsIncluded; }

  public String getPerExtra100() { return perExtra100; }
  public void setPerExtra100(String perExtra100) { this.perExtra100 = perExtra100; }

  public String getWeeksIncluded() { return weeksIncluded; }
  public void setWeeksIncluded(String weeksIncluded) { this.weeksIncluded = weeksIncluded; }

  public String getPerExtraWeek() { return perExtraWeek; }
  public void setPerExtraWeek(String perExtraWeek) { this.perExtraWeek = perExtraWeek; }

  public String getJudgingFees() { return judgingFees; }
  public void setJudgingFees(String judgingFees) { this.judgingFees = judgingFees; }

  public Double getPermitAssistanceFee() { return permitAssistanceFee; }
  public void setPermitAssistanceFee(Double permitAssistanceFee) { this.permitAssistanceFee = permitAssistanceFee; }

  public Double getPrizeAdminPct() { return prizeAdminPct; }
  public void setPrizeAdminPct(Double prizeAdminPct) { this.prizeAdminPct = prizeAdminPct; }

  public String getAddonFees() { return addonFees; }
  public void setAddonFees(String addonFees) { this.addonFees = addonFees; }

  public String getProgramDiscounts() { return programDiscounts; }
  public void setProgramDiscounts(String programDiscounts) { this.programDiscounts = programDiscounts; }

  public Double getGstPct() { return gstPct; }
  public void setGstPct(Double gstPct) { this.gstPct = gstPct; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
