package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `regulatory_rule_version` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "regulatory_rule_version")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class RegulatoryRuleVersionEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "rule_code", length = 255)
  private String ruleCode;

  @Column(name = "version_number")
  private Double versionNumber;

  @Column(name = "condition_expression", columnDefinition = "LONGTEXT")
  private String conditionExpression;

  @Column(name = "obligation_type", length = 64)
  private String obligationType;

  @Column(name = "detail", columnDefinition = "LONGTEXT")
  private String detail;

  @Column(name = "blocking")
  private Boolean blocking;

  @Column(name = "satisfied_by", length = 64)
  private String satisfiedBy;

  @Column(name = "gate", length = 64)
  private String gate;

  @Column(name = "effective_from")
  private Instant effectiveFrom;

  @Column(name = "legal_signoff", columnDefinition = "LONGTEXT")
  private String legalSignoff;

  @Column(name = "is_current")
  private Boolean isCurrent;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getRuleCode() { return ruleCode; }
  public void setRuleCode(String ruleCode) { this.ruleCode = ruleCode; }

  public Double getVersionNumber() { return versionNumber; }
  public void setVersionNumber(Double versionNumber) { this.versionNumber = versionNumber; }

  public String getConditionExpression() { return conditionExpression; }
  public void setConditionExpression(String conditionExpression) { this.conditionExpression = conditionExpression; }

  public String getObligationType() { return obligationType; }
  public void setObligationType(String obligationType) { this.obligationType = obligationType; }

  public String getDetail() { return detail; }
  public void setDetail(String detail) { this.detail = detail; }

  public Boolean getBlocking() { return blocking; }
  public void setBlocking(Boolean blocking) { this.blocking = blocking; }

  public String getSatisfiedBy() { return satisfiedBy; }
  public void setSatisfiedBy(String satisfiedBy) { this.satisfiedBy = satisfiedBy; }

  public String getGate() { return gate; }
  public void setGate(String gate) { this.gate = gate; }

  public Instant getEffectiveFrom() { return effectiveFrom; }
  public void setEffectiveFrom(Instant effectiveFrom) { this.effectiveFrom = effectiveFrom; }

  public String getLegalSignoff() { return legalSignoff; }
  public void setLegalSignoff(String legalSignoff) { this.legalSignoff = legalSignoff; }

  public Boolean getIsCurrent() { return isCurrent; }
  public void setIsCurrent(Boolean isCurrent) { this.isCurrent = isCurrent; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
