package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `rights_grant_template` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "rights_grant_template")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class RightsGrantTemplateEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "scope_code", length = 255)
  private String scopeCode;

  @Column(name = "tier", length = 64)
  private String tier;

  @Column(name = "display_name", length = 255)
  private String displayName;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "clause_reference", length = 255)
  private String clauseReference;

  @Column(name = "default_duration", length = 255)
  private String defaultDuration;

  @Column(name = "default_territory", length = 255)
  private String defaultTerritory;

  @Column(name = "default_attribution")
  private Boolean defaultAttribution;

  @Column(name = "default_sublicensable")
  private Boolean defaultSublicensable;

  @Column(name = "default_revocable")
  private Boolean defaultRevocable;

  @Column(name = "version")
  private Double version;

  @Column(name = "legal_signoff", columnDefinition = "LONGTEXT")
  private String legalSignoff;

  @Column(name = "is_current")
  private Boolean isCurrent;

  @Column(name = "effective_from")
  private Instant effectiveFrom;

  @Column(name = "retirement_date")
  private Instant retirementDate;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getScopeCode() { return scopeCode; }
  public void setScopeCode(String scopeCode) { this.scopeCode = scopeCode; }

  public String getTier() { return tier; }
  public void setTier(String tier) { this.tier = tier; }

  public String getDisplayName() { return displayName; }
  public void setDisplayName(String displayName) { this.displayName = displayName; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public String getClauseReference() { return clauseReference; }
  public void setClauseReference(String clauseReference) { this.clauseReference = clauseReference; }

  public String getDefaultDuration() { return defaultDuration; }
  public void setDefaultDuration(String defaultDuration) { this.defaultDuration = defaultDuration; }

  public String getDefaultTerritory() { return defaultTerritory; }
  public void setDefaultTerritory(String defaultTerritory) { this.defaultTerritory = defaultTerritory; }

  public Boolean getDefaultAttribution() { return defaultAttribution; }
  public void setDefaultAttribution(Boolean defaultAttribution) { this.defaultAttribution = defaultAttribution; }

  public Boolean getDefaultSublicensable() { return defaultSublicensable; }
  public void setDefaultSublicensable(Boolean defaultSublicensable) { this.defaultSublicensable = defaultSublicensable; }

  public Boolean getDefaultRevocable() { return defaultRevocable; }
  public void setDefaultRevocable(Boolean defaultRevocable) { this.defaultRevocable = defaultRevocable; }

  public Double getVersion() { return version; }
  public void setVersion(Double version) { this.version = version; }

  public String getLegalSignoff() { return legalSignoff; }
  public void setLegalSignoff(String legalSignoff) { this.legalSignoff = legalSignoff; }

  public Boolean getIsCurrent() { return isCurrent; }
  public void setIsCurrent(Boolean isCurrent) { this.isCurrent = isCurrent; }

  public Instant getEffectiveFrom() { return effectiveFrom; }
  public void setEffectiveFrom(Instant effectiveFrom) { this.effectiveFrom = effectiveFrom; }

  public Instant getRetirementDate() { return retirementDate; }
  public void setRetirementDate(Instant retirementDate) { this.retirementDate = retirementDate; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
