package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `saved_quote` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "saved_quote")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class SavedQuoteEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "rate_card_id", length = 255)
  private String rateCardId;

  @Column(name = "rate_card_version")
  private Double rateCardVersion;

  @Column(name = "configuration", columnDefinition = "LONGTEXT")
  private String configuration;

  @Column(name = "computed_lines", columnDefinition = "LONGTEXT")
  private String computedLines;

  @Column(name = "subtotal")
  private Double subtotal;

  @Column(name = "gst")
  private Double gst;

  @Column(name = "total")
  private Double total;

  @Column(name = "is_enterprise")
  private Boolean isEnterprise;

  @Column(name = "created_for", length = 255)
  private String createdFor;

  @Column(name = "intake_response_id", length = 255)
  private String intakeResponseId;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getRateCardId() { return rateCardId; }
  public void setRateCardId(String rateCardId) { this.rateCardId = rateCardId; }

  public Double getRateCardVersion() { return rateCardVersion; }
  public void setRateCardVersion(Double rateCardVersion) { this.rateCardVersion = rateCardVersion; }

  public String getConfiguration() { return configuration; }
  public void setConfiguration(String configuration) { this.configuration = configuration; }

  public String getComputedLines() { return computedLines; }
  public void setComputedLines(String computedLines) { this.computedLines = computedLines; }

  public Double getSubtotal() { return subtotal; }
  public void setSubtotal(Double subtotal) { this.subtotal = subtotal; }

  public Double getGst() { return gst; }
  public void setGst(Double gst) { this.gst = gst; }

  public Double getTotal() { return total; }
  public void setTotal(Double total) { this.total = total; }

  public Boolean getIsEnterprise() { return isEnterprise; }
  public void setIsEnterprise(Boolean isEnterprise) { this.isEnterprise = isEnterprise; }

  public String getCreatedFor() { return createdFor; }
  public void setCreatedFor(String createdFor) { this.createdFor = createdFor; }

  public String getIntakeResponseId() { return intakeResponseId; }
  public void setIntakeResponseId(String intakeResponseId) { this.intakeResponseId = intakeResponseId; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
