package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `score` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "score")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ScoreEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "panel_id", length = 255)
  private String panelId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "anonymous_id", length = 255)
  private String anonymousId;

  @Column(name = "judge_profile_id", length = 1024)
  private String judgeProfileId;

  @Column(name = "judge_name", length = 255)
  private String judgeName;

  @Column(name = "scores", columnDefinition = "LONGTEXT")
  private String scores;

  @Column(name = "comments", columnDefinition = "LONGTEXT")
  private String comments;

  @Column(name = "compliance_flagged")
  private Boolean complianceFlagged;

  @Column(name = "compliance_reason", length = 64)
  private String complianceReason;

  @Column(name = "compliance_note", columnDefinition = "LONGTEXT")
  private String complianceNote;

  @Column(name = "compliance_status", length = 64)
  private String complianceStatus;

  @Column(name = "compliance_resolved_by", length = 255)
  private String complianceResolvedBy;

  @Column(name = "compliance_resolved_at")
  private Instant complianceResolvedAt;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "submitted_at")
  private Instant submittedAt;

  @Column(name = "amendment_reason", columnDefinition = "LONGTEXT")
  private String amendmentReason;

  @Column(name = "amended_by", length = 255)
  private String amendedBy;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPanelId() { return panelId; }
  public void setPanelId(String panelId) { this.panelId = panelId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getAnonymousId() { return anonymousId; }
  public void setAnonymousId(String anonymousId) { this.anonymousId = anonymousId; }

  public String getJudgeProfileId() { return judgeProfileId; }
  public void setJudgeProfileId(String judgeProfileId) { this.judgeProfileId = judgeProfileId; }

  public String getJudgeName() { return judgeName; }
  public void setJudgeName(String judgeName) { this.judgeName = judgeName; }

  public String getScores() { return scores; }
  public void setScores(String scores) { this.scores = scores; }

  public String getComments() { return comments; }
  public void setComments(String comments) { this.comments = comments; }

  public Boolean getComplianceFlagged() { return complianceFlagged; }
  public void setComplianceFlagged(Boolean complianceFlagged) { this.complianceFlagged = complianceFlagged; }

  public String getComplianceReason() { return complianceReason; }
  public void setComplianceReason(String complianceReason) { this.complianceReason = complianceReason; }

  public String getComplianceNote() { return complianceNote; }
  public void setComplianceNote(String complianceNote) { this.complianceNote = complianceNote; }

  public String getComplianceStatus() { return complianceStatus; }
  public void setComplianceStatus(String complianceStatus) { this.complianceStatus = complianceStatus; }

  public String getComplianceResolvedBy() { return complianceResolvedBy; }
  public void setComplianceResolvedBy(String complianceResolvedBy) { this.complianceResolvedBy = complianceResolvedBy; }

  public Instant getComplianceResolvedAt() { return complianceResolvedAt; }
  public void setComplianceResolvedAt(Instant complianceResolvedAt) { this.complianceResolvedAt = complianceResolvedAt; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getSubmittedAt() { return submittedAt; }
  public void setSubmittedAt(Instant submittedAt) { this.submittedAt = submittedAt; }

  public String getAmendmentReason() { return amendmentReason; }
  public void setAmendmentReason(String amendmentReason) { this.amendmentReason = amendmentReason; }

  public String getAmendedBy() { return amendedBy; }
  public void setAmendedBy(String amendedBy) { this.amendedBy = amendedBy; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
