package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `scoring_model` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "scoring_model")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ScoringModelEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "slug", length = 255)
  private String slug;

  @Column(name = "automatic")
  private Boolean automatic;

  @Column(name = "judge_weight")
  private Double judgeWeight;

  @Column(name = "public_weight")
  private Double publicWeight;

  @Column(name = "judge_blind")
  private Boolean judgeBlind;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getSlug() { return slug; }
  public void setSlug(String slug) { this.slug = slug; }

  public Boolean getAutomatic() { return automatic; }
  public void setAutomatic(Boolean automatic) { this.automatic = automatic; }

  public Double getJudgeWeight() { return judgeWeight; }
  public void setJudgeWeight(Double judgeWeight) { this.judgeWeight = judgeWeight; }

  public Double getPublicWeight() { return publicWeight; }
  public void setPublicWeight(Double publicWeight) { this.publicWeight = publicWeight; }

  public Boolean getJudgeBlind() { return judgeBlind; }
  public void setJudgeBlind(Boolean judgeBlind) { this.judgeBlind = judgeBlind; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
