package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `series_standing` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "series_standing")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class SeriesStandingEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "pathway_id", length = 255)
  private String pathwayId;

  @Column(name = "creator_name", length = 255)
  private String creatorName;

  @Column(name = "creator_email", length = 255)
  private String creatorEmail;

  @Column(name = "state", length = 255)
  private String state;

  @Column(name = "total_points")
  private Double totalPoints;

  @Column(name = "events_counted")
  private Double eventsCounted;

  @Column(name = "best_placing")
  private Double bestPlacing;

  @Column(name = "`rank`")
  private Double rank;

  @Column(name = "breakdown", columnDefinition = "LONGTEXT")
  private String breakdown;

  @Column(name = "computed_at")
  private Instant computedAt;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getPathwayId() { return pathwayId; }
  public void setPathwayId(String pathwayId) { this.pathwayId = pathwayId; }

  public String getCreatorName() { return creatorName; }
  public void setCreatorName(String creatorName) { this.creatorName = creatorName; }

  public String getCreatorEmail() { return creatorEmail; }
  public void setCreatorEmail(String creatorEmail) { this.creatorEmail = creatorEmail; }

  public String getState() { return state; }
  public void setState(String state) { this.state = state; }

  public Double getTotalPoints() { return totalPoints; }
  public void setTotalPoints(Double totalPoints) { this.totalPoints = totalPoints; }

  public Double getEventsCounted() { return eventsCounted; }
  public void setEventsCounted(Double eventsCounted) { this.eventsCounted = eventsCounted; }

  public Double getBestPlacing() { return bestPlacing; }
  public void setBestPlacing(Double bestPlacing) { this.bestPlacing = bestPlacing; }

  public Double getRank() { return rank; }
  public void setRank(Double rank) { this.rank = rank; }

  public String getBreakdown() { return breakdown; }
  public void setBreakdown(String breakdown) { this.breakdown = breakdown; }

  public Instant getComputedAt() { return computedAt; }
  public void setComputedAt(Instant computedAt) { this.computedAt = computedAt; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
