package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `subcategory` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "subcategory")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class SubcategoryEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "name", length = 255)
  private String name;

  @Column(name = "category", length = 255)
  private String category;

  @Column(name = "category_id", length = 255)
  private String categoryId;

  @Column(name = "slug", length = 255)
  private String slug;

  @Column(name = "is_active")
  private Boolean isActive;

  @Column(name = "sort_order")
  private Double sortOrder;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "module_key", length = 255)
  private String moduleKey;

  @Column(name = "description", columnDefinition = "LONGTEXT")
  private String description;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getName() { return name; }
  public void setName(String name) { this.name = name; }

  public String getCategory() { return category; }
  public void setCategory(String category) { this.category = category; }

  public String getCategoryId() { return categoryId; }
  public void setCategoryId(String categoryId) { this.categoryId = categoryId; }

  public String getSlug() { return slug; }
  public void setSlug(String slug) { this.slug = slug; }

  public Boolean getIsActive() { return isActive; }
  public void setIsActive(Boolean isActive) { this.isActive = isActive; }

  public Double getSortOrder() { return sortOrder; }
  public void setSortOrder(Double sortOrder) { this.sortOrder = sortOrder; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public String getModuleKey() { return moduleKey; }
  public void setModuleKey(String moduleKey) { this.moduleKey = moduleKey; }

  public String getDescription() { return description; }
  public void setDescription(String description) { this.description = description; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
