package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `terms_document` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "terms_document")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class TermsDocumentEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "clause_versions_used", columnDefinition = "LONGTEXT")
  private String clauseVersionsUsed;

  @Column(name = "merged_output", length = 255)
  private String mergedOutput;

  @Column(name = "status", length = 64)
  private String status;

  @Column(name = "published_at")
  private Instant publishedAt;

  @Column(name = "superseded_by", length = 255)
  private String supersededBy;

  @Column(name = "change_note", columnDefinition = "LONGTEXT")
  private String changeNote;

  @Column(name = "config_snapshot", columnDefinition = "LONGTEXT")
  private String configSnapshot;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getClauseVersionsUsed() { return clauseVersionsUsed; }
  public void setClauseVersionsUsed(String clauseVersionsUsed) { this.clauseVersionsUsed = clauseVersionsUsed; }

  public String getMergedOutput() { return mergedOutput; }
  public void setMergedOutput(String mergedOutput) { this.mergedOutput = mergedOutput; }

  public String getStatus() { return status; }
  public void setStatus(String status) { this.status = status; }

  public Instant getPublishedAt() { return publishedAt; }
  public void setPublishedAt(Instant publishedAt) { this.publishedAt = publishedAt; }

  public String getSupersededBy() { return supersededBy; }
  public void setSupersededBy(String supersededBy) { this.supersededBy = supersededBy; }

  public String getChangeNote() { return changeNote; }
  public void setChangeNote(String changeNote) { this.changeNote = changeNote; }

  public String getConfigSnapshot() { return configSnapshot; }
  public void setConfigSnapshot(String configSnapshot) { this.configSnapshot = configSnapshot; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
