package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `vote_audit_log` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "vote_audit_log")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class VoteAuditLogEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "vote_id", length = 255)
  private String voteId;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "entry_id", length = 255)
  private String entryId;

  @Column(name = "actor", length = 255)
  private String actor;

  @Column(name = "action", length = 64)
  private String action;

  @Column(name = "reason", columnDefinition = "LONGTEXT")
  private String reason;

  @Column(name = "at")
  private Instant at;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getVoteId() { return voteId; }
  public void setVoteId(String voteId) { this.voteId = voteId; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getEntryId() { return entryId; }
  public void setEntryId(String entryId) { this.entryId = entryId; }

  public String getActor() { return actor; }
  public void setActor(String actor) { this.actor = actor; }

  public String getAction() { return action; }
  public void setAction(String action) { this.action = action; }

  public String getReason() { return reason; }
  public void setReason(String reason) { this.reason = reason; }

  public Instant getAt() { return at; }
  public void setAt(Instant at) { this.at = at; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
