package com.fiftythree.challenges.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;

/**
 * Maps the `voting_configuration` table. Generated by migration/generate-entities.cjs from
 * schema.sql — do not edit by hand; add the table to SKIP there if it needs
 * custom behaviour.
 *
 * <p>Serialised snake_case so a record returned straight to the client matches
 * the shape the Base44 entity API produced.
 */
@Entity
@Table(name = "voting_configuration")
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class VotingConfigurationEntity {

  @Id
  @Column(name = "id", length = 24, nullable = false)
  private String id;

  @Column(name = "challenge_id", length = 255)
  private String challengeId;

  @Column(name = "voting_purpose", length = 64)
  private String votingPurpose;

  @Column(name = "weight_in_final_result")
  private Double weightInFinalResult;

  @Column(name = "paid_voting")
  private Boolean paidVoting;

  @Column(name = "bonus_or_referral_votes")
  private Boolean bonusOrReferralVotes;

  @Column(name = "votes_per_person_per_account")
  private Double votesPerPersonPerAccount;

  @Column(name = "votes_per_person_per_device")
  private Double votesPerPersonPerDevice;

  @Column(name = "votes_per_person_per_period")
  private Double votesPerPersonPerPeriod;

  @Column(name = "identity_verification", length = 64)
  private String identityVerification;

  @Column(name = "geographic_restrictions", columnDefinition = "LONGTEXT")
  private String geographicRestrictions;

  @Column(name = "anti_bot_controls", columnDefinition = "LONGTEXT")
  private String antiBotControls;

  @Column(name = "live_totals_public")
  private Boolean liveTotalsPublic;

  @Column(name = "vote_audit_procedure", length = 255)
  private String voteAuditProcedure;

  @Column(name = "tie_break_rule", length = 255)
  private String tieBreakRule;

  @Column(name = "moderator_adjustment_authority")
  private Boolean moderatorAdjustmentAuthority;

  @Column(name = "judges_can_override")
  private Boolean judgesCanOverride;

  @Column(name = "legal_opinion_reference", length = 255)
  private String legalOpinionReference;

  @Column(name = "created_date")
  private Instant createdDate;

  @Column(name = "updated_date")
  private Instant updatedDate;

  @Column(name = "created_by_id", length = 64)
  private String createdById;

  @Column(name = "is_sample")
  private Boolean isSample;
  public String getId() { return id; }
  public void setId(String id) { this.id = id; }

  public String getChallengeId() { return challengeId; }
  public void setChallengeId(String challengeId) { this.challengeId = challengeId; }

  public String getVotingPurpose() { return votingPurpose; }
  public void setVotingPurpose(String votingPurpose) { this.votingPurpose = votingPurpose; }

  public Double getWeightInFinalResult() { return weightInFinalResult; }
  public void setWeightInFinalResult(Double weightInFinalResult) { this.weightInFinalResult = weightInFinalResult; }

  public Boolean getPaidVoting() { return paidVoting; }
  public void setPaidVoting(Boolean paidVoting) { this.paidVoting = paidVoting; }

  public Boolean getBonusOrReferralVotes() { return bonusOrReferralVotes; }
  public void setBonusOrReferralVotes(Boolean bonusOrReferralVotes) { this.bonusOrReferralVotes = bonusOrReferralVotes; }

  public Double getVotesPerPersonPerAccount() { return votesPerPersonPerAccount; }
  public void setVotesPerPersonPerAccount(Double votesPerPersonPerAccount) { this.votesPerPersonPerAccount = votesPerPersonPerAccount; }

  public Double getVotesPerPersonPerDevice() { return votesPerPersonPerDevice; }
  public void setVotesPerPersonPerDevice(Double votesPerPersonPerDevice) { this.votesPerPersonPerDevice = votesPerPersonPerDevice; }

  public Double getVotesPerPersonPerPeriod() { return votesPerPersonPerPeriod; }
  public void setVotesPerPersonPerPeriod(Double votesPerPersonPerPeriod) { this.votesPerPersonPerPeriod = votesPerPersonPerPeriod; }

  public String getIdentityVerification() { return identityVerification; }
  public void setIdentityVerification(String identityVerification) { this.identityVerification = identityVerification; }

  public String getGeographicRestrictions() { return geographicRestrictions; }
  public void setGeographicRestrictions(String geographicRestrictions) { this.geographicRestrictions = geographicRestrictions; }

  public String getAntiBotControls() { return antiBotControls; }
  public void setAntiBotControls(String antiBotControls) { this.antiBotControls = antiBotControls; }

  public Boolean getLiveTotalsPublic() { return liveTotalsPublic; }
  public void setLiveTotalsPublic(Boolean liveTotalsPublic) { this.liveTotalsPublic = liveTotalsPublic; }

  public String getVoteAuditProcedure() { return voteAuditProcedure; }
  public void setVoteAuditProcedure(String voteAuditProcedure) { this.voteAuditProcedure = voteAuditProcedure; }

  public String getTieBreakRule() { return tieBreakRule; }
  public void setTieBreakRule(String tieBreakRule) { this.tieBreakRule = tieBreakRule; }

  public Boolean getModeratorAdjustmentAuthority() { return moderatorAdjustmentAuthority; }
  public void setModeratorAdjustmentAuthority(Boolean moderatorAdjustmentAuthority) { this.moderatorAdjustmentAuthority = moderatorAdjustmentAuthority; }

  public Boolean getJudgesCanOverride() { return judgesCanOverride; }
  public void setJudgesCanOverride(Boolean judgesCanOverride) { this.judgesCanOverride = judgesCanOverride; }

  public String getLegalOpinionReference() { return legalOpinionReference; }
  public void setLegalOpinionReference(String legalOpinionReference) { this.legalOpinionReference = legalOpinionReference; }

  public Instant getCreatedDate() { return createdDate; }
  public void setCreatedDate(Instant createdDate) { this.createdDate = createdDate; }

  public Instant getUpdatedDate() { return updatedDate; }
  public void setUpdatedDate(Instant updatedDate) { this.updatedDate = updatedDate; }

  public String getCreatedById() { return createdById; }
  public void setCreatedById(String createdById) { this.createdById = createdById; }

  public Boolean getIsSample() { return isSample; }
  public void setIsSample(Boolean isSample) { this.isSample = isSample; }
}
